/**
 * PDF builders for the enforcement package flow. Uses pdf-lib which runs on
 * Cloudflare Workers without native deps. Produces three artifacts:
 *   1. Evidence Package  — finding metadata, timestamps, claims, fact checks.
 *   2. Authorization Package — legal name, signature record, vault reference.
 *   3. Platform Complaint Package — narrative + fields from platform templates.
 */

import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { ComplaintPayload } from "./platform-templates.server";

export interface EvidenceInput {
  finding: {
    id: string;
    title: string;
    url: string;
    source: string;
    platform: string;
    severity: string | null;
    threatScore: number | null;
    author: string | null;
    publishedAt: string | null;
    description: string | null;
  };
  timestamps: Array<{ startSeconds: number; endSeconds: number | null; excerpt: string; severity?: string | null }>;
  claims: Array<{ extracted: string; claimant: string | null; status: string | null }>;
  factChecks: Array<{ publisher: string; title: string; url: string; rating: string | null }>;
  evidenceFrames: Array<{ frameSeconds: number; description: string | null }>;
  capturedAt: string;
  contentHash: string;
}

export interface AuthorizationInput {
  legalName: string;
  email: string | null;
  country: string | null;
  authorizationLevel: string;
  signatureText: string | null;
  signedAt: string | null;
  signatureHash: string | null;
  ipAddress: string | null;
  userAgent: string | null;
  clientType: string | null;
  requestSummary: string;
}

function makePainter(pdf: PDFDocument, font: import("pdf-lib").PDFFont, bold: import("pdf-lib").PDFFont) {
  let page = pdf.addPage([595.28, 841.89]); // A4
  const margin = 50;
  let y = 800;

  const newPage = () => { page = pdf.addPage([595.28, 841.89]); y = 800; };
  const ensure = (needed: number) => { if (y - needed < margin) newPage(); };

  const heading = (text: string, size = 16) => {
    ensure(size + 12);
    page.drawText(text, { x: margin, y, size, font: bold, color: rgb(0.08, 0.08, 0.15) });
    y -= size + 8;
  };
  const subheading = (text: string) => {
    ensure(20);
    y -= 4;
    page.drawText(text, { x: margin, y, size: 11, font: bold, color: rgb(0.25, 0.25, 0.4) });
    y -= 14;
  };
  const line = (text: string, opts?: { small?: boolean; muted?: boolean; indent?: number }) => {
    const size = opts?.small ? 9 : 10;
    const color = opts?.muted ? rgb(0.45, 0.45, 0.5) : rgb(0.1, 0.1, 0.15);
    const indent = opts?.indent ?? 0;
    const maxWidth = 495 - indent;
    // basic word wrap
    const words = (text ?? "").split(/\s+/);
    let buf = "";
    for (const w of words) {
      const test = buf ? `${buf} ${w}` : w;
      if (font.widthOfTextAtSize(test, size) > maxWidth) {
        ensure(size + 4);
        page.drawText(buf, { x: margin + indent, y, size, font, color });
        y -= size + 3;
        buf = w;
      } else {
        buf = test;
      }
    }
    if (buf) {
      ensure(size + 4);
      page.drawText(buf, { x: margin + indent, y, size, font, color });
      y -= size + 3;
    }
  };
  const spacer = (h = 8) => { y -= h; };
  const rule = () => { ensure(6); page.drawLine({ start: { x: margin, y }, end: { x: 545, y }, thickness: 0.5, color: rgb(0.8, 0.8, 0.85) }); y -= 8; };

  return { heading, subheading, line, spacer, rule };
}

async function baseDoc(title: string) {
  const pdf = await PDFDocument.create();
  pdf.setTitle(title);
  pdf.setProducer("Eterna AI");
  pdf.setCreator("Eterna AI Enforcement");
  const font = await pdf.embedFont(StandardFonts.Helvetica);
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  return { pdf, font, bold };
}

export async function buildEvidencePdf(input: EvidenceInput): Promise<Uint8Array> {
  const { pdf, font, bold } = await baseDoc(`Evidence Package — ${input.finding.title}`);
  const p = makePainter(pdf, font, bold);

  p.heading("EVIDENCE PACKAGE", 18);
  p.line(`Generated by Eterna AI on ${new Date(input.capturedAt).toLocaleString()}`, { muted: true, small: true });
  p.line(`Content SHA-256: ${input.contentHash}`, { muted: true, small: true });
  p.spacer();
  p.rule();

  p.subheading("Finding");
  p.line(`Title: ${input.finding.title}`);
  p.line(`URL: ${input.finding.url}`);
  p.line(`Source / platform: ${input.finding.source} · ${input.finding.platform}`);
  p.line(`Severity: ${input.finding.severity ?? "—"}   Threat score: ${input.finding.threatScore ?? "—"}`);
  if (input.finding.author) p.line(`Author / channel: ${input.finding.author}`);
  if (input.finding.publishedAt) p.line(`Published: ${input.finding.publishedAt}`);
  if (input.finding.description) { p.spacer(4); p.line(input.finding.description, { small: true, muted: true }); }

  p.spacer(); p.rule();
  p.subheading(`Timestamped evidence (${input.timestamps.length})`);
  if (!input.timestamps.length) p.line("No timestamped evidence segments captured.", { muted: true, small: true });
  for (const t of input.timestamps.slice(0, 40)) {
    p.line(`[${fmtTime(t.startSeconds)}${t.endSeconds ? "–" + fmtTime(t.endSeconds) : ""}] ${t.severity ? `(${t.severity}) ` : ""}${t.excerpt}`, { indent: 8 });
  }

  p.spacer(); p.rule();
  p.subheading(`Extracted claims (${input.claims.length})`);
  if (!input.claims.length) p.line("No searchable claims extracted.", { muted: true, small: true });
  for (const c of input.claims.slice(0, 40)) {
    p.line(`• ${c.extracted}${c.claimant ? ` — attributed to ${c.claimant}` : ""}${c.status ? ` [${c.status}]` : ""}`, { indent: 8 });
  }

  p.spacer(); p.rule();
  p.subheading(`Independent fact-check matches (${input.factChecks.length})`);
  if (!input.factChecks.length) p.line("No independent fact-check reviews located.", { muted: true, small: true });
  for (const f of input.factChecks.slice(0, 30)) {
    p.line(`• ${f.publisher}: ${f.title}${f.rating ? ` — ${f.rating}` : ""}`, { indent: 8 });
    p.line(f.url, { indent: 16, small: true, muted: true });
  }

  if (input.evidenceFrames.length) {
    p.spacer(); p.rule();
    p.subheading(`Frame-level evidence (${input.evidenceFrames.length})`);
    for (const fr of input.evidenceFrames.slice(0, 30)) {
      p.line(`[${fmtTime(fr.frameSeconds)}] ${fr.description ?? ""}`, { indent: 8 });
    }
  }

  p.spacer(); p.rule();
  p.line(
    "This document was compiled from public web content collected via Eterna AI's automated intelligence pipeline. Threat and reputation scores are analytical estimates, not legal findings.",
    { small: true, muted: true },
  );

  return await pdf.save();
}

export async function buildAuthorizationPdf(input: AuthorizationInput): Promise<Uint8Array> {
  const { pdf, font, bold } = await baseDoc(`Authorization Package — ${input.legalName}`);
  const p = makePainter(pdf, font, bold);

  p.heading("AUTHORIZATION PACKAGE", 18);
  p.line("This package certifies the complainant's authorization to submit the associated enforcement request.", { muted: true, small: true });
  p.spacer(); p.rule();

  p.subheading("Complainant identity");
  p.line(`Legal name: ${input.legalName}`);
  if (input.email) p.line(`Email: ${input.email}`);
  if (input.country) p.line(`Country: ${input.country}`);
  if (input.clientType) p.line(`Client type: ${input.clientType}`);

  p.spacer(); p.rule();
  p.subheading("Authorization record");
  p.line(`Authorization level: ${input.authorizationLevel}`);
  if (input.signatureText) p.line(`Electronic signature: ${input.signatureText}`);
  if (input.signedAt) p.line(`Signed at: ${input.signedAt}`);
  if (input.signatureHash) p.line(`Signature hash: ${input.signatureHash}`, { small: true, muted: true });
  if (input.ipAddress) p.line(`Signed from IP: ${input.ipAddress}`, { small: true, muted: true });
  if (input.userAgent) p.line(`User agent: ${input.userAgent}`, { small: true, muted: true });

  p.spacer(); p.rule();
  p.subheading("Request scope");
  p.line(input.requestSummary);

  p.spacer(); p.rule();
  p.line(
    "I declare under penalty of perjury that I am authorized to submit this notice on behalf of the rights holder, and that the information contained in the associated enforcement request is accurate.",
    { small: true },
  );

  return await pdf.save();
}

export async function buildComplaintPdf(complaint: ComplaintPayload, targetTitle: string): Promise<Uint8Array> {
  const { pdf, font, bold } = await baseDoc(`Complaint — ${targetTitle}`);
  const p = makePainter(pdf, font, bold);

  p.heading(`${complaint.platform.toUpperCase()} COMPLAINT`, 18);
  p.line(`Complaint kind: ${complaint.kind}`, { small: true, muted: true });
  if (complaint.submissionUrl) p.line(`Official submission URL: ${complaint.submissionUrl}`, { small: true, muted: true });
  p.line(`Evidence strength: ${complaint.evidenceStrength}`, { small: true, muted: true });
  p.spacer(); p.rule();

  p.subheading("Form field values");
  for (const [k, v] of Object.entries(complaint.fields)) {
    p.line(`${k}: ${v || "—"}`, { indent: 8 });
  }

  p.spacer(); p.rule();
  p.subheading("Narrative statement");
  for (const paragraph of complaint.narrative.split("\n")) {
    p.line(paragraph || " ");
  }

  return await pdf.save();
}

function fmtTime(sec: number): string {
  const s = Math.max(0, Math.round(sec));
  const h = Math.floor(s / 3600);
  const m = Math.floor((s % 3600) / 60);
  const r = s % 60;
  return h > 0 ? `${h}:${String(m).padStart(2, "0")}:${String(r).padStart(2, "0")}` : `${m}:${String(r).padStart(2, "0")}`;
}
