/**
 * Fetches lawful, publicly-available YouTube caption tracks and returns
 * timestamped segments. We NEVER synthesize timestamps: if no timestamped
 * track is available, we return an empty result and callers must render
 * "Metadata-only analysis — exact spoken-content timestamps are unavailable."
 *
 * Strategy:
 *   1. Fetch the public watch-page HTML.
 *   2. Parse `ytInitialPlayerResponse.captions.playerCaptionsTracklistRenderer.captionTracks`.
 *   3. Pick the best track (manual over ASR, preferred language over others).
 *   4. Fetch the track XML (`baseUrl`) and parse the `<text start="…" dur="…">` nodes.
 *
 * If YouTube changes its embed structure or the video has no accessible
 * captions, we return { available: false } — no fabrication.
 */

export interface CaptionTrackInfo {
  languageCode: string;
  name?: string;
  isAutoGenerated: boolean;
  baseUrl: string;
}

export interface TimedCaptionSegment {
  index: number;
  startSeconds: number;
  endSeconds: number;
  text: string;
}

export interface FetchCaptionsResult {
  available: boolean;
  reason?: string;
  language?: string;
  isAutoGenerated?: boolean;
  source?: "youtube_caption";
  segments?: TimedCaptionSegment[];
  coveragePct?: number;
  tracks?: CaptionTrackInfo[];
}

function decodeXml(s: string): string {
  return s
    .replace(/&amp;/g, "&")
    .replace(/&lt;/g, "<")
    .replace(/&gt;/g, ">")
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))
    .replace(/<[^>]+>/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

async function fetchWatchHtml(videoId: string): Promise<string | null> {
  try {
    const r = await fetch(`https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`, {
      headers: {
        // A realistic UA is required or YT will serve a stripped page without ytInitialPlayerResponse.
        "user-agent":
          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
        "accept-language": "en-US,en;q=0.9",
      },
    });
    if (!r.ok) return null;
    return await r.text();
  } catch {
    return null;
  }
}

function extractCaptionTracks(html: string): CaptionTrackInfo[] {
  // ytInitialPlayerResponse is embedded as a JS assignment.
  const marker = "ytInitialPlayerResponse";
  const idx = html.indexOf(marker);
  if (idx < 0) return [];
  // Slice a window big enough to contain the JSON payload.
  const window = html.slice(idx, idx + 400000);
  // Find the first '{' after "="
  const eq = window.indexOf("=");
  if (eq < 0) return [];
  let start = eq + 1;
  while (start < window.length && window[start] !== "{") start++;
  if (window[start] !== "{") return [];
  // Balanced-brace scan (naive but effective for this payload).
  let depth = 0;
  let end = start;
  let inStr = false;
  let esc = false;
  for (; end < window.length; end++) {
    const c = window[end];
    if (inStr) {
      if (esc) esc = false;
      else if (c === "\\") esc = true;
      else if (c === '"') inStr = false;
      continue;
    }
    if (c === '"') { inStr = true; continue; }
    if (c === "{") depth++;
    else if (c === "}") { depth--; if (depth === 0) { end++; break; } }
  }
  const jsonText = window.slice(start, end);
  let obj: unknown;
  try { obj = JSON.parse(jsonText); } catch { return []; }
  const tracks =
    (obj as { captions?: { playerCaptionsTracklistRenderer?: { captionTracks?: unknown[] } } })
      ?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!Array.isArray(tracks)) return [];
  const out: CaptionTrackInfo[] = [];
  for (const t of tracks) {
    if (!t || typeof t !== "object") continue;
    const rec = t as Record<string, unknown>;
    const baseUrl = typeof rec.baseUrl === "string" ? rec.baseUrl : "";
    const languageCode = typeof rec.languageCode === "string" ? rec.languageCode : "";
    if (!baseUrl || !languageCode) continue;
    const kind = typeof rec.kind === "string" ? rec.kind : "";
    const nameObj = rec.name as { simpleText?: string; runs?: Array<{ text?: string }> } | undefined;
    const name = nameObj?.simpleText ?? nameObj?.runs?.[0]?.text;
    out.push({
      languageCode,
      name,
      isAutoGenerated: kind === "asr",
      baseUrl,
    });
  }
  return out;
}

function pickTrack(tracks: CaptionTrackInfo[], prefer: string[]): CaptionTrackInfo | null {
  if (!tracks.length) return null;
  const norm = (s: string) => s.toLowerCase().split("-")[0];
  // Priority: manual + preferred language > manual + english > manual any > asr preferred > asr english > asr any
  const wantList = prefer.length ? prefer.map(norm) : ["en"];
  const byLang = (list: CaptionTrackInfo[], lang: string, auto: boolean) =>
    list.find((t) => norm(t.languageCode) === lang && t.isAutoGenerated === auto);
  for (const w of wantList) { const t = byLang(tracks, w, false); if (t) return t; }
  const enManual = byLang(tracks, "en", false); if (enManual) return enManual;
  const anyManual = tracks.find((t) => !t.isAutoGenerated); if (anyManual) return anyManual;
  for (const w of wantList) { const t = byLang(tracks, w, true); if (t) return t; }
  const enAsr = byLang(tracks, "en", true); if (enAsr) return enAsr;
  return tracks[0];
}

function parseTimedTextXml(xml: string): TimedCaptionSegment[] {
  const out: TimedCaptionSegment[] = [];
  const re = /<text\b([^>]*)>([\s\S]*?)<\/text>/g;
  let m: RegExpExecArray | null;
  let i = 0;
  while ((m = re.exec(xml))) {
    const attrs = m[1] ?? "";
    const startMatch = /start="([\d.]+)"/.exec(attrs);
    const durMatch = /dur="([\d.]+)"/.exec(attrs);
    if (!startMatch) continue;
    const startSeconds = Number(startMatch[1]);
    const dur = durMatch ? Number(durMatch[1]) : 2;
    const text = decodeXml(m[2] ?? "");
    if (!text) continue;
    out.push({
      index: i++,
      startSeconds,
      endSeconds: startSeconds + dur,
      text,
    });
  }
  return out;
}

/** Public entry point. */
export async function fetchYoutubeCaptions(
  videoId: string,
  preferredLanguages: string[] = [],
): Promise<FetchCaptionsResult> {
  const html = await fetchWatchHtml(videoId);
  if (!html) return { available: false, reason: "watch_page_unreachable" };
  const tracks = extractCaptionTracks(html);
  if (!tracks.length) return { available: false, reason: "no_caption_tracks", tracks: [] };
  const chosen = pickTrack(tracks, preferredLanguages);
  if (!chosen) return { available: false, reason: "no_selectable_track", tracks };
  let trackUrl = chosen.baseUrl;
  // The default baseUrl returns YouTube's XML timedtext. That's what we want.
  if (!/[?&]fmt=/.test(trackUrl)) trackUrl += "&fmt=srv3";
  try {
    const r = await fetch(trackUrl, {
      headers: {
        "user-agent":
          "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
      },
    });
    if (!r.ok) return { available: false, reason: `track_fetch_${r.status}`, tracks };
    const xml = await r.text();
    const segments = parseTimedTextXml(xml);
    if (!segments.length) return { available: false, reason: "empty_track", tracks };
    return {
      available: true,
      language: chosen.languageCode,
      isAutoGenerated: chosen.isAutoGenerated,
      source: "youtube_caption",
      segments,
      coveragePct: undefined,
      tracks,
    };
  } catch {
    return { available: false, reason: "track_fetch_failed", tracks };
  }
}
