/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as VerifySlugRouteImport } from './routes/verify.$slug'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as AppThreatRadarRouteImport } from './routes/_app.threat-radar'
import { Route as AppThreatMonitoringRouteImport } from './routes/_app.threat-monitoring'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRemovalsRouteImport } from './routes/_app.removals'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNarrativeIntelligenceRouteImport } from './routes/_app.narrative-intelligence'
import { Route as AppIntelligenceRouteImport } from './routes/_app.intelligence'
import { Route as AppFaceProtectionRouteImport } from './routes/_app.face-protection'
import { Route as AppEvidenceVaultRouteImport } from './routes/_app.evidence-vault'
import { Route as AppEnforcementRouteImport } from './routes/_app.enforcement'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as AppSensitiveProtectionIndexRouteImport } from './routes/_app.sensitive-protection.index'
import { Route as ApiPublicVeriffWebhookRouteImport } from './routes/api/public/veriff-webhook'
import { Route as ApiMediaPreviewRouteImport } from './routes/api/media.preview'
import { Route as AppSensitiveProtectionRemovalCasesRouteImport } from './routes/_app.sensitive-protection.removal-cases'
import { Route as AppSensitiveProtectionEmergencyRouteImport } from './routes/_app.sensitive-protection.emergency'
import { Route as AppAdminSensitiveProtectionRouteImport } from './routes/_app.admin.sensitive-protection'
import { Route as AppAdminProviderActivationRouteImport } from './routes/_app.admin.provider-activation'
import { Route as AppAdminOnboardingReviewsRouteImport } from './routes/_app.admin.onboarding-reviews'
import { Route as AppAdminMultimediaHealthRouteImport } from './routes/_app.admin.multimedia-health'
import { Route as AppAdminDiagnosticsRouteImport } from './routes/_app.admin.diagnostics'
import { Route as AppSensitiveProtectionResultsIndexRouteImport } from './routes/_app.sensitive-protection.results.index'
import { Route as ApiPublicHooksChannelWatchPollRouteImport } from './routes/api/public/hooks/channel-watch-poll'
import { Route as AppSensitiveProtectionResultsIdRouteImport } from './routes/_app.sensitive-protection.results.$id'

const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const VerifySlugRoute = VerifySlugRouteImport.update({
  id: '/verify/$slug',
  path: '/verify/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const AppThreatRadarRoute = AppThreatRadarRouteImport.update({
  id: '/threat-radar',
  path: '/threat-radar',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatMonitoringRoute = AppThreatMonitoringRouteImport.update({
  id: '/threat-monitoring',
  path: '/threat-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRemovalsRoute = AppRemovalsRouteImport.update({
  id: '/removals',
  path: '/removals',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNarrativeIntelligenceRoute =
  AppNarrativeIntelligenceRouteImport.update({
    id: '/narrative-intelligence',
    path: '/narrative-intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppFaceProtectionRoute = AppFaceProtectionRouteImport.update({
  id: '/face-protection',
  path: '/face-protection',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceVaultRoute = AppEvidenceVaultRouteImport.update({
  id: '/evidence-vault',
  path: '/evidence-vault',
  getParentRoute: () => AppRoute,
} as any)
const AppEnforcementRoute = AppEnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const AppSensitiveProtectionIndexRoute =
  AppSensitiveProtectionIndexRouteImport.update({
    id: '/sensitive-protection/',
    path: '/sensitive-protection/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicVeriffWebhookRoute = ApiPublicVeriffWebhookRouteImport.update({
  id: '/api/public/veriff-webhook',
  path: '/api/public/veriff-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaPreviewRoute = ApiMediaPreviewRouteImport.update({
  id: '/api/media/preview',
  path: '/api/media/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSensitiveProtectionRemovalCasesRoute =
  AppSensitiveProtectionRemovalCasesRouteImport.update({
    id: '/sensitive-protection/removal-cases',
    path: '/sensitive-protection/removal-cases',
    getParentRoute: () => AppRoute,
  } as any)
const AppSensitiveProtectionEmergencyRoute =
  AppSensitiveProtectionEmergencyRouteImport.update({
    id: '/sensitive-protection/emergency',
    path: '/sensitive-protection/emergency',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminSensitiveProtectionRoute =
  AppAdminSensitiveProtectionRouteImport.update({
    id: '/admin/sensitive-protection',
    path: '/admin/sensitive-protection',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminProviderActivationRoute =
  AppAdminProviderActivationRouteImport.update({
    id: '/admin/provider-activation',
    path: '/admin/provider-activation',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminOnboardingReviewsRoute =
  AppAdminOnboardingReviewsRouteImport.update({
    id: '/admin/onboarding-reviews',
    path: '/admin/onboarding-reviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminMultimediaHealthRoute =
  AppAdminMultimediaHealthRouteImport.update({
    id: '/admin/multimedia-health',
    path: '/admin/multimedia-health',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminDiagnosticsRoute = AppAdminDiagnosticsRouteImport.update({
  id: '/admin/diagnostics',
  path: '/admin/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppSensitiveProtectionResultsIndexRoute =
  AppSensitiveProtectionResultsIndexRouteImport.update({
    id: '/sensitive-protection/results/',
    path: '/sensitive-protection/results/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksChannelWatchPollRoute =
  ApiPublicHooksChannelWatchPollRouteImport.update({
    id: '/api/public/hooks/channel-watch-poll',
    path: '/api/public/hooks/channel-watch-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSensitiveProtectionResultsIdRoute =
  AppSensitiveProtectionResultsIdRouteImport.update({
    id: '/sensitive-protection/results/$id',
    path: '/sensitive-protection/results/$id',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/assets': typeof AppAssetsRoute
  '/cases': typeof AppCasesRoute
  '/enforcement': typeof AppEnforcementRoute
  '/evidence-vault': typeof AppEvidenceVaultRoute
  '/face-protection': typeof AppFaceProtectionRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/narrative-intelligence': typeof AppNarrativeIntelligenceRoute
  '/notifications': typeof AppNotificationsRoute
  '/removals': typeof AppRemovalsRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/threat-monitoring': typeof AppThreatMonitoringRoute
  '/threat-radar': typeof AppThreatRadarRoute
  '/api/scan': typeof ApiScanRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/admin/multimedia-health': typeof AppAdminMultimediaHealthRoute
  '/admin/onboarding-reviews': typeof AppAdminOnboardingReviewsRoute
  '/admin/provider-activation': typeof AppAdminProviderActivationRoute
  '/admin/sensitive-protection': typeof AppAdminSensitiveProtectionRoute
  '/sensitive-protection/emergency': typeof AppSensitiveProtectionEmergencyRoute
  '/sensitive-protection/removal-cases': typeof AppSensitiveProtectionRemovalCasesRoute
  '/api/media/preview': typeof ApiMediaPreviewRoute
  '/api/public/veriff-webhook': typeof ApiPublicVeriffWebhookRoute
  '/sensitive-protection/': typeof AppSensitiveProtectionIndexRoute
  '/sensitive-protection/results/$id': typeof AppSensitiveProtectionResultsIdRoute
  '/api/public/hooks/channel-watch-poll': typeof ApiPublicHooksChannelWatchPollRoute
  '/sensitive-protection/results/': typeof AppSensitiveProtectionResultsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/assets': typeof AppAssetsRoute
  '/cases': typeof AppCasesRoute
  '/enforcement': typeof AppEnforcementRoute
  '/evidence-vault': typeof AppEvidenceVaultRoute
  '/face-protection': typeof AppFaceProtectionRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/narrative-intelligence': typeof AppNarrativeIntelligenceRoute
  '/notifications': typeof AppNotificationsRoute
  '/removals': typeof AppRemovalsRoute
  '/reports': typeof AppReportsRoute
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/threat-monitoring': typeof AppThreatMonitoringRoute
  '/threat-radar': typeof AppThreatRadarRoute
  '/api/scan': typeof ApiScanRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/': typeof AppIndexRoute
  '/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/admin/multimedia-health': typeof AppAdminMultimediaHealthRoute
  '/admin/onboarding-reviews': typeof AppAdminOnboardingReviewsRoute
  '/admin/provider-activation': typeof AppAdminProviderActivationRoute
  '/admin/sensitive-protection': typeof AppAdminSensitiveProtectionRoute
  '/sensitive-protection/emergency': typeof AppSensitiveProtectionEmergencyRoute
  '/sensitive-protection/removal-cases': typeof AppSensitiveProtectionRemovalCasesRoute
  '/api/media/preview': typeof ApiMediaPreviewRoute
  '/api/public/veriff-webhook': typeof ApiPublicVeriffWebhookRoute
  '/sensitive-protection': typeof AppSensitiveProtectionIndexRoute
  '/sensitive-protection/results/$id': typeof AppSensitiveProtectionResultsIdRoute
  '/api/public/hooks/channel-watch-poll': typeof ApiPublicHooksChannelWatchPollRoute
  '/sensitive-protection/results': typeof AppSensitiveProtectionResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacy': typeof PrivacyRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/enforcement': typeof AppEnforcementRoute
  '/_app/evidence-vault': typeof AppEvidenceVaultRoute
  '/_app/face-protection': typeof AppFaceProtectionRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/narrative-intelligence': typeof AppNarrativeIntelligenceRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/removals': typeof AppRemovalsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/threat-monitoring': typeof AppThreatMonitoringRoute
  '/_app/threat-radar': typeof AppThreatRadarRoute
  '/api/scan': typeof ApiScanRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/_app/': typeof AppIndexRoute
  '/_app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/_app/admin/multimedia-health': typeof AppAdminMultimediaHealthRoute
  '/_app/admin/onboarding-reviews': typeof AppAdminOnboardingReviewsRoute
  '/_app/admin/provider-activation': typeof AppAdminProviderActivationRoute
  '/_app/admin/sensitive-protection': typeof AppAdminSensitiveProtectionRoute
  '/_app/sensitive-protection/emergency': typeof AppSensitiveProtectionEmergencyRoute
  '/_app/sensitive-protection/removal-cases': typeof AppSensitiveProtectionRemovalCasesRoute
  '/api/media/preview': typeof ApiMediaPreviewRoute
  '/api/public/veriff-webhook': typeof ApiPublicVeriffWebhookRoute
  '/_app/sensitive-protection/': typeof AppSensitiveProtectionIndexRoute
  '/_app/sensitive-protection/results/$id': typeof AppSensitiveProtectionResultsIdRoute
  '/api/public/hooks/channel-watch-poll': typeof ApiPublicHooksChannelWatchPollRoute
  '/_app/sensitive-protection/results/': typeof AppSensitiveProtectionResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/assets'
    | '/cases'
    | '/enforcement'
    | '/evidence-vault'
    | '/face-protection'
    | '/intelligence'
    | '/narrative-intelligence'
    | '/notifications'
    | '/removals'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/threat-monitoring'
    | '/threat-radar'
    | '/api/scan'
    | '/verify/$slug'
    | '/admin/diagnostics'
    | '/admin/multimedia-health'
    | '/admin/onboarding-reviews'
    | '/admin/provider-activation'
    | '/admin/sensitive-protection'
    | '/sensitive-protection/emergency'
    | '/sensitive-protection/removal-cases'
    | '/api/media/preview'
    | '/api/public/veriff-webhook'
    | '/sensitive-protection/'
    | '/sensitive-protection/results/$id'
    | '/api/public/hooks/channel-watch-poll'
    | '/sensitive-protection/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/assets'
    | '/cases'
    | '/enforcement'
    | '/evidence-vault'
    | '/face-protection'
    | '/intelligence'
    | '/narrative-intelligence'
    | '/notifications'
    | '/removals'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/threat-monitoring'
    | '/threat-radar'
    | '/api/scan'
    | '/verify/$slug'
    | '/'
    | '/admin/diagnostics'
    | '/admin/multimedia-health'
    | '/admin/onboarding-reviews'
    | '/admin/provider-activation'
    | '/admin/sensitive-protection'
    | '/sensitive-protection/emergency'
    | '/sensitive-protection/removal-cases'
    | '/api/media/preview'
    | '/api/public/veriff-webhook'
    | '/sensitive-protection'
    | '/sensitive-protection/results/$id'
    | '/api/public/hooks/channel-watch-poll'
    | '/sensitive-protection/results'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/onboarding'
    | '/privacy'
    | '/_app/assets'
    | '/_app/cases'
    | '/_app/enforcement'
    | '/_app/evidence-vault'
    | '/_app/face-protection'
    | '/_app/intelligence'
    | '/_app/narrative-intelligence'
    | '/_app/notifications'
    | '/_app/removals'
    | '/_app/reports'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/threat-monitoring'
    | '/_app/threat-radar'
    | '/api/scan'
    | '/verify/$slug'
    | '/_app/'
    | '/_app/admin/diagnostics'
    | '/_app/admin/multimedia-health'
    | '/_app/admin/onboarding-reviews'
    | '/_app/admin/provider-activation'
    | '/_app/admin/sensitive-protection'
    | '/_app/sensitive-protection/emergency'
    | '/_app/sensitive-protection/removal-cases'
    | '/api/media/preview'
    | '/api/public/veriff-webhook'
    | '/_app/sensitive-protection/'
    | '/_app/sensitive-protection/results/$id'
    | '/api/public/hooks/channel-watch-poll'
    | '/_app/sensitive-protection/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacyRoute: typeof PrivacyRoute
  ApiScanRoute: typeof ApiScanRoute
  VerifySlugRoute: typeof VerifySlugRoute
  ApiMediaPreviewRoute: typeof ApiMediaPreviewRoute
  ApiPublicVeriffWebhookRoute: typeof ApiPublicVeriffWebhookRoute
  ApiPublicHooksChannelWatchPollRoute: typeof ApiPublicHooksChannelWatchPollRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/verify/$slug': {
      id: '/verify/$slug'
      path: '/verify/$slug'
      fullPath: '/verify/$slug'
      preLoaderRoute: typeof VerifySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/threat-radar': {
      id: '/_app/threat-radar'
      path: '/threat-radar'
      fullPath: '/threat-radar'
      preLoaderRoute: typeof AppThreatRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threat-monitoring': {
      id: '/_app/threat-monitoring'
      path: '/threat-monitoring'
      fullPath: '/threat-monitoring'
      preLoaderRoute: typeof AppThreatMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/removals': {
      id: '/_app/removals'
      path: '/removals'
      fullPath: '/removals'
      preLoaderRoute: typeof AppRemovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/narrative-intelligence': {
      id: '/_app/narrative-intelligence'
      path: '/narrative-intelligence'
      fullPath: '/narrative-intelligence'
      preLoaderRoute: typeof AppNarrativeIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/face-protection': {
      id: '/_app/face-protection'
      path: '/face-protection'
      fullPath: '/face-protection'
      preLoaderRoute: typeof AppFaceProtectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence-vault': {
      id: '/_app/evidence-vault'
      path: '/evidence-vault'
      fullPath: '/evidence-vault'
      preLoaderRoute: typeof AppEvidenceVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enforcement': {
      id: '/_app/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof AppEnforcementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensitive-protection/': {
      id: '/_app/sensitive-protection/'
      path: '/sensitive-protection'
      fullPath: '/sensitive-protection/'
      preLoaderRoute: typeof AppSensitiveProtectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/veriff-webhook': {
      id: '/api/public/veriff-webhook'
      path: '/api/public/veriff-webhook'
      fullPath: '/api/public/veriff-webhook'
      preLoaderRoute: typeof ApiPublicVeriffWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/preview': {
      id: '/api/media/preview'
      path: '/api/media/preview'
      fullPath: '/api/media/preview'
      preLoaderRoute: typeof ApiMediaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sensitive-protection/removal-cases': {
      id: '/_app/sensitive-protection/removal-cases'
      path: '/sensitive-protection/removal-cases'
      fullPath: '/sensitive-protection/removal-cases'
      preLoaderRoute: typeof AppSensitiveProtectionRemovalCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensitive-protection/emergency': {
      id: '/_app/sensitive-protection/emergency'
      path: '/sensitive-protection/emergency'
      fullPath: '/sensitive-protection/emergency'
      preLoaderRoute: typeof AppSensitiveProtectionEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sensitive-protection': {
      id: '/_app/admin/sensitive-protection'
      path: '/admin/sensitive-protection'
      fullPath: '/admin/sensitive-protection'
      preLoaderRoute: typeof AppAdminSensitiveProtectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/provider-activation': {
      id: '/_app/admin/provider-activation'
      path: '/admin/provider-activation'
      fullPath: '/admin/provider-activation'
      preLoaderRoute: typeof AppAdminProviderActivationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/onboarding-reviews': {
      id: '/_app/admin/onboarding-reviews'
      path: '/admin/onboarding-reviews'
      fullPath: '/admin/onboarding-reviews'
      preLoaderRoute: typeof AppAdminOnboardingReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/multimedia-health': {
      id: '/_app/admin/multimedia-health'
      path: '/admin/multimedia-health'
      fullPath: '/admin/multimedia-health'
      preLoaderRoute: typeof AppAdminMultimediaHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/diagnostics': {
      id: '/_app/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AppAdminDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensitive-protection/results/': {
      id: '/_app/sensitive-protection/results/'
      path: '/sensitive-protection/results'
      fullPath: '/sensitive-protection/results/'
      preLoaderRoute: typeof AppSensitiveProtectionResultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/channel-watch-poll': {
      id: '/api/public/hooks/channel-watch-poll'
      path: '/api/public/hooks/channel-watch-poll'
      fullPath: '/api/public/hooks/channel-watch-poll'
      preLoaderRoute: typeof ApiPublicHooksChannelWatchPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sensitive-protection/results/$id': {
      id: '/_app/sensitive-protection/results/$id'
      path: '/sensitive-protection/results/$id'
      fullPath: '/sensitive-protection/results/$id'
      preLoaderRoute: typeof AppSensitiveProtectionResultsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppCasesRoute: typeof AppCasesRoute
  AppEnforcementRoute: typeof AppEnforcementRoute
  AppEvidenceVaultRoute: typeof AppEvidenceVaultRoute
  AppFaceProtectionRoute: typeof AppFaceProtectionRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppNarrativeIntelligenceRoute: typeof AppNarrativeIntelligenceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRemovalsRoute: typeof AppRemovalsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThreatMonitoringRoute: typeof AppThreatMonitoringRoute
  AppThreatRadarRoute: typeof AppThreatRadarRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAdminDiagnosticsRoute: typeof AppAdminDiagnosticsRoute
  AppAdminMultimediaHealthRoute: typeof AppAdminMultimediaHealthRoute
  AppAdminOnboardingReviewsRoute: typeof AppAdminOnboardingReviewsRoute
  AppAdminProviderActivationRoute: typeof AppAdminProviderActivationRoute
  AppAdminSensitiveProtectionRoute: typeof AppAdminSensitiveProtectionRoute
  AppSensitiveProtectionEmergencyRoute: typeof AppSensitiveProtectionEmergencyRoute
  AppSensitiveProtectionRemovalCasesRoute: typeof AppSensitiveProtectionRemovalCasesRoute
  AppSensitiveProtectionIndexRoute: typeof AppSensitiveProtectionIndexRoute
  AppSensitiveProtectionResultsIdRoute: typeof AppSensitiveProtectionResultsIdRoute
  AppSensitiveProtectionResultsIndexRoute: typeof AppSensitiveProtectionResultsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppCasesRoute: AppCasesRoute,
  AppEnforcementRoute: AppEnforcementRoute,
  AppEvidenceVaultRoute: AppEvidenceVaultRoute,
  AppFaceProtectionRoute: AppFaceProtectionRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppNarrativeIntelligenceRoute: AppNarrativeIntelligenceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRemovalsRoute: AppRemovalsRoute,
  AppReportsRoute: AppReportsRoute,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThreatMonitoringRoute: AppThreatMonitoringRoute,
  AppThreatRadarRoute: AppThreatRadarRoute,
  AppIndexRoute: AppIndexRoute,
  AppAdminDiagnosticsRoute: AppAdminDiagnosticsRoute,
  AppAdminMultimediaHealthRoute: AppAdminMultimediaHealthRoute,
  AppAdminOnboardingReviewsRoute: AppAdminOnboardingReviewsRoute,
  AppAdminProviderActivationRoute: AppAdminProviderActivationRoute,
  AppAdminSensitiveProtectionRoute: AppAdminSensitiveProtectionRoute,
  AppSensitiveProtectionEmergencyRoute: AppSensitiveProtectionEmergencyRoute,
  AppSensitiveProtectionRemovalCasesRoute:
    AppSensitiveProtectionRemovalCasesRoute,
  AppSensitiveProtectionIndexRoute: AppSensitiveProtectionIndexRoute,
  AppSensitiveProtectionResultsIdRoute: AppSensitiveProtectionResultsIdRoute,
  AppSensitiveProtectionResultsIndexRoute:
    AppSensitiveProtectionResultsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacyRoute: PrivacyRoute,
  ApiScanRoute: ApiScanRoute,
  VerifySlugRoute: VerifySlugRoute,
  ApiMediaPreviewRoute: ApiMediaPreviewRoute,
  ApiPublicVeriffWebhookRoute: ApiPublicVeriffWebhookRoute,
  ApiPublicHooksChannelWatchPollRoute: ApiPublicHooksChannelWatchPollRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
