/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitinglistRouteImport } from './routes/waitinglist'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PartnerStatusRouteImport } from './routes/partner-status'
import { Route as PartnerApplyRouteImport } from './routes/partner-apply'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NewsroomRouteImport } from './routes/newsroom'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as IdentityResponseObservatoryRouteImport } from './routes/identity-response-observatory'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AgentAssessmentRouteImport } from './routes/agent-assessment'
import { Route as AgentAdminRouteImport } from './routes/agent-admin'
import { Route as AgentRouteImport } from './routes/agent'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AboutRouteImport } from './routes/about'
import { Route as PartnerRouteImport } from './routes/_partner'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VerifySlugRouteImport } from './routes/verify.$slug'
import { Route as NewsroomImpersonationResponseGuideRouteImport } from './routes/newsroom_.impersonation-response-guide'
import { Route as NewsroomExecutiveFirstHourPlaybookRouteImport } from './routes/newsroom_.executive-first-hour-playbook'
import { Route as NewsroomDeepfakeVerificationGuideRouteImport } from './routes/newsroom_.deepfake-verification-guide'
import { Route as FaceHandoffTokenRouteImport } from './routes/face-handoff.$token'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as PartnerPartnerRouteImport } from './routes/_partner.partner'
import { Route as AppYoutubeRemovalRouteImport } from './routes/_app.youtube-removal'
import { Route as AppThreatRadarRouteImport } from './routes/_app.threat-radar'
import { Route as AppThreatMonitoringRouteImport } from './routes/_app.threat-monitoring'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScanRouteImport } from './routes/_app.scan'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppRemovalsRouteImport } from './routes/_app.removals'
import { Route as AppNotificationsRouteImport } from './routes/_app.notifications'
import { Route as AppNarrativeIntelligenceRouteImport } from './routes/_app.narrative-intelligence'
import { Route as AppIntelligenceRouteImport } from './routes/_app.intelligence'
import { Route as AppFaceReferencesRouteImport } from './routes/_app.face-references'
import { Route as AppFaceProtectionRouteImport } from './routes/_app.face-protection'
import { Route as AppEvidenceVaultRouteImport } from './routes/_app.evidence-vault'
import { Route as AppEnforcementRouteImport } from './routes/_app.enforcement'
import { Route as AppDeepfakeIntelRouteImport } from './routes/_app.deepfake-intel'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCopyrightIntelRouteImport } from './routes/_app.copyright-intel'
import { Route as AppChannelWatchRouteImport } from './routes/_app.channel-watch'
import { Route as AppCasesRouteImport } from './routes/_app.cases'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppAssetsRouteImport } from './routes/_app.assets'
import { Route as PartnerPartnerIndexRouteImport } from './routes/_partner.partner.index'
import { Route as AppSensitiveProtectionIndexRouteImport } from './routes/_app.sensitive-protection.index'
import { Route as ApiPublicVeriffWebhookRouteImport } from './routes/api/public/veriff-webhook'
import { Route as ApiPublicOnboardingCompletionBackfillRouteImport } from './routes/api/public/onboarding-completion-backfill'
import { Route as ApiPublicImageProxyRouteImport } from './routes/api/public/image-proxy'
import { Route as ApiMediaPreviewRouteImport } from './routes/api/media.preview'
import { Route as PartnerPartnerProposalsRouteImport } from './routes/_partner.partner.proposals'
import { Route as PartnerPartnerPaymentsRouteImport } from './routes/_partner.partner.payments'
import { Route as PartnerPartnerMarketingRouteImport } from './routes/_partner.partner.marketing'
import { Route as PartnerPartnerCommissionsRouteImport } from './routes/_partner.partner.commissions'
import { Route as PartnerPartnerClientsRouteImport } from './routes/_partner.partner.clients'
import { Route as AppSensitiveProtectionRemovalCasesRouteImport } from './routes/_app.sensitive-protection.removal-cases'
import { Route as AppSensitiveProtectionEmergencyRouteImport } from './routes/_app.sensitive-protection.emergency'
import { Route as AppReportsReportIdRouteImport } from './routes/_app.reports.$reportId'
import { Route as AppProtectionSourcesRouteImport } from './routes/_app.protection.sources'
import { Route as AppAdminWaitlistRouteImport } from './routes/_app.admin.waitlist'
import { Route as AppAdminSensitiveProtectionRouteImport } from './routes/_app.admin.sensitive-protection'
import { Route as AppAdminRemovalRoutesRouteImport } from './routes/_app.admin.removal-routes'
import { Route as AppAdminProviderActivationRouteImport } from './routes/_app.admin.provider-activation'
import { Route as AppAdminOnboardingReviewsRouteImport } from './routes/_app.admin.onboarding-reviews'
import { Route as AppAdminMultimediaHealthRouteImport } from './routes/_app.admin.multimedia-health'
import { Route as AppAdminInvitesRouteImport } from './routes/_app.admin.invites'
import { Route as AppAdminIdentityReviewRouteImport } from './routes/_app.admin.identity-review'
import { Route as AppAdminDiagnosticsRouteImport } from './routes/_app.admin.diagnostics'
import { Route as AppAdminApprovedSourcesReviewRouteImport } from './routes/_app.admin.approved-sources-review'
import { Route as AppSensitiveProtectionResultsIndexRouteImport } from './routes/_app.sensitive-protection.results.index'
import { Route as ApiPublicHooksScanOrchestratorRouteImport } from './routes/api/public/hooks/scan-orchestrator'
import { Route as ApiPublicHooksResendWebhookRouteImport } from './routes/api/public/hooks/resend-webhook'
import { Route as ApiPublicHooksReleaseProtectionMonitorRouteImport } from './routes/api/public/hooks/release-protection-monitor'
import { Route as ApiPublicHooksProtectionSchedulerTokenRouteImport } from './routes/api/public/hooks/protection-scheduler-token'
import { Route as ApiPublicHooksProtectionAutopilotRouteImport } from './routes/api/public/hooks/protection-autopilot'
import { Route as ApiPublicHooksProtectionActivationRepairRouteImport } from './routes/api/public/hooks/protection-activation-repair'
import { Route as ApiPublicHooksPostmarkWebhookRouteImport } from './routes/api/public/hooks/postmark-webhook'
import { Route as ApiPublicHooksEnforcementWorkerRouteImport } from './routes/api/public/hooks/enforcement-worker'
import { Route as ApiPublicHooksDistributionMonitorRouteImport } from './routes/api/public/hooks/distribution-monitor'
import { Route as ApiPublicHooksDeepfakeScanExecuteRouteImport } from './routes/api/public/hooks/deepfake-scan-execute'
import { Route as ApiPublicHooksDeepfakeManualEvidenceExecuteRouteImport } from './routes/api/public/hooks/deepfake-manual-evidence-execute'
import { Route as ApiPublicHooksDeepfakeGoogleImagesWorkerRouteImport } from './routes/api/public/hooks/deepfake-google-images-worker'
import { Route as ApiPublicHooksCopyrightScanExecuteRouteImport } from './routes/api/public/hooks/copyright-scan-execute'
import { Route as ApiPublicHooksChannelWatchPollRouteImport } from './routes/api/public/hooks/channel-watch-poll'
import { Route as ApiPublicHooksAutomationStatusRouteImport } from './routes/api/public/hooks/automation-status'
import { Route as ApiPublicHooksAutomationFetchRouteImport } from './routes/api/public/hooks/automation-fetch'
import { Route as ApiPublicHooksApprovedSourcesPollRouteImport } from './routes/api/public/hooks/approved-sources-poll'
import { Route as ApiPublicHooksAgentAssessmentsRouteImport } from './routes/api/public/hooks/agent-assessments'
import { Route as AppSensitiveProtectionResultsIdRouteImport } from './routes/_app.sensitive-protection.results.$id'

const WaitinglistRoute = WaitinglistRouteImport.update({
  id: '/waitinglist',
  path: '/waitinglist',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerStatusRoute = PartnerStatusRouteImport.update({
  id: '/partner-status',
  path: '/partner-status',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerApplyRoute = PartnerApplyRouteImport.update({
  id: '/partner-apply',
  path: '/partner-apply',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomRoute = NewsroomRouteImport.update({
  id: '/newsroom',
  path: '/newsroom',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const IdentityResponseObservatoryRoute =
  IdentityResponseObservatoryRouteImport.update({
    id: '/identity-response-observatory',
    path: '/identity-response-observatory',
    getParentRoute: () => rootRouteImport,
  } as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAssessmentRoute = AgentAssessmentRouteImport.update({
  id: '/agent-assessment',
  path: '/agent-assessment',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentAdminRoute = AgentAdminRouteImport.update({
  id: '/agent-admin',
  path: '/agent-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentRoute = AgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/_partner',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifySlugRoute = VerifySlugRouteImport.update({
  id: '/verify/$slug',
  path: '/verify/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsroomImpersonationResponseGuideRoute =
  NewsroomImpersonationResponseGuideRouteImport.update({
    id: '/newsroom_/impersonation-response-guide',
    path: '/newsroom/impersonation-response-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsroomExecutiveFirstHourPlaybookRoute =
  NewsroomExecutiveFirstHourPlaybookRouteImport.update({
    id: '/newsroom_/executive-first-hour-playbook',
    path: '/newsroom/executive-first-hour-playbook',
    getParentRoute: () => rootRouteImport,
  } as any)
const NewsroomDeepfakeVerificationGuideRoute =
  NewsroomDeepfakeVerificationGuideRouteImport.update({
    id: '/newsroom_/deepfake-verification-guide',
    path: '/newsroom/deepfake-verification-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const FaceHandoffTokenRoute = FaceHandoffTokenRouteImport.update({
  id: '/face-handoff/$token',
  path: '/face-handoff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPartnerRoute = PartnerPartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => PartnerRoute,
} as any)
const AppYoutubeRemovalRoute = AppYoutubeRemovalRouteImport.update({
  id: '/youtube-removal',
  path: '/youtube-removal',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatRadarRoute = AppThreatRadarRouteImport.update({
  id: '/threat-radar',
  path: '/threat-radar',
  getParentRoute: () => AppRoute,
} as any)
const AppThreatMonitoringRoute = AppThreatMonitoringRouteImport.update({
  id: '/threat-monitoring',
  path: '/threat-monitoring',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScanRoute = AppScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppRemovalsRoute = AppRemovalsRouteImport.update({
  id: '/removals',
  path: '/removals',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppNarrativeIntelligenceRoute =
  AppNarrativeIntelligenceRouteImport.update({
    id: '/narrative-intelligence',
    path: '/narrative-intelligence',
    getParentRoute: () => AppRoute,
  } as any)
const AppIntelligenceRoute = AppIntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => AppRoute,
} as any)
const AppFaceReferencesRoute = AppFaceReferencesRouteImport.update({
  id: '/face-references',
  path: '/face-references',
  getParentRoute: () => AppRoute,
} as any)
const AppFaceProtectionRoute = AppFaceProtectionRouteImport.update({
  id: '/face-protection',
  path: '/face-protection',
  getParentRoute: () => AppRoute,
} as any)
const AppEvidenceVaultRoute = AppEvidenceVaultRouteImport.update({
  id: '/evidence-vault',
  path: '/evidence-vault',
  getParentRoute: () => AppRoute,
} as any)
const AppEnforcementRoute = AppEnforcementRouteImport.update({
  id: '/enforcement',
  path: '/enforcement',
  getParentRoute: () => AppRoute,
} as any)
const AppDeepfakeIntelRoute = AppDeepfakeIntelRouteImport.update({
  id: '/deepfake-intel',
  path: '/deepfake-intel',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCopyrightIntelRoute = AppCopyrightIntelRouteImport.update({
  id: '/copyright-intel',
  path: '/copyright-intel',
  getParentRoute: () => AppRoute,
} as any)
const AppChannelWatchRoute = AppChannelWatchRouteImport.update({
  id: '/channel-watch',
  path: '/channel-watch',
  getParentRoute: () => AppRoute,
} as any)
const AppCasesRoute = AppCasesRouteImport.update({
  id: '/cases',
  path: '/cases',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAssetsRoute = AppAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => AppRoute,
} as any)
const PartnerPartnerIndexRoute = PartnerPartnerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PartnerPartnerRoute,
} as any)
const AppSensitiveProtectionIndexRoute =
  AppSensitiveProtectionIndexRouteImport.update({
    id: '/sensitive-protection/',
    path: '/sensitive-protection/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicVeriffWebhookRoute = ApiPublicVeriffWebhookRouteImport.update({
  id: '/api/public/veriff-webhook',
  path: '/api/public/veriff-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOnboardingCompletionBackfillRoute =
  ApiPublicOnboardingCompletionBackfillRouteImport.update({
    id: '/api/public/onboarding-completion-backfill',
    path: '/api/public/onboarding-completion-backfill',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicImageProxyRoute = ApiPublicImageProxyRouteImport.update({
  id: '/api/public/image-proxy',
  path: '/api/public/image-proxy',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMediaPreviewRoute = ApiMediaPreviewRouteImport.update({
  id: '/api/media/preview',
  path: '/api/media/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerPartnerProposalsRoute = PartnerPartnerProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => PartnerPartnerRoute,
} as any)
const PartnerPartnerPaymentsRoute = PartnerPartnerPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => PartnerPartnerRoute,
} as any)
const PartnerPartnerMarketingRoute = PartnerPartnerMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => PartnerPartnerRoute,
} as any)
const PartnerPartnerCommissionsRoute =
  PartnerPartnerCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => PartnerPartnerRoute,
  } as any)
const PartnerPartnerClientsRoute = PartnerPartnerClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => PartnerPartnerRoute,
} as any)
const AppSensitiveProtectionRemovalCasesRoute =
  AppSensitiveProtectionRemovalCasesRouteImport.update({
    id: '/sensitive-protection/removal-cases',
    path: '/sensitive-protection/removal-cases',
    getParentRoute: () => AppRoute,
  } as any)
const AppSensitiveProtectionEmergencyRoute =
  AppSensitiveProtectionEmergencyRouteImport.update({
    id: '/sensitive-protection/emergency',
    path: '/sensitive-protection/emergency',
    getParentRoute: () => AppRoute,
  } as any)
const AppReportsReportIdRoute = AppReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => AppReportsRoute,
} as any)
const AppProtectionSourcesRoute = AppProtectionSourcesRouteImport.update({
  id: '/protection/sources',
  path: '/protection/sources',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminWaitlistRoute = AppAdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminSensitiveProtectionRoute =
  AppAdminSensitiveProtectionRouteImport.update({
    id: '/admin/sensitive-protection',
    path: '/admin/sensitive-protection',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminRemovalRoutesRoute = AppAdminRemovalRoutesRouteImport.update({
  id: '/admin/removal-routes',
  path: '/admin/removal-routes',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminProviderActivationRoute =
  AppAdminProviderActivationRouteImport.update({
    id: '/admin/provider-activation',
    path: '/admin/provider-activation',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminOnboardingReviewsRoute =
  AppAdminOnboardingReviewsRouteImport.update({
    id: '/admin/onboarding-reviews',
    path: '/admin/onboarding-reviews',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminMultimediaHealthRoute =
  AppAdminMultimediaHealthRouteImport.update({
    id: '/admin/multimedia-health',
    path: '/admin/multimedia-health',
    getParentRoute: () => AppRoute,
  } as any)
const AppAdminInvitesRoute = AppAdminInvitesRouteImport.update({
  id: '/admin/invites',
  path: '/admin/invites',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminIdentityReviewRoute = AppAdminIdentityReviewRouteImport.update({
  id: '/admin/identity-review',
  path: '/admin/identity-review',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminDiagnosticsRoute = AppAdminDiagnosticsRouteImport.update({
  id: '/admin/diagnostics',
  path: '/admin/diagnostics',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminApprovedSourcesReviewRoute =
  AppAdminApprovedSourcesReviewRouteImport.update({
    id: '/admin/approved-sources-review',
    path: '/admin/approved-sources-review',
    getParentRoute: () => AppRoute,
  } as any)
const AppSensitiveProtectionResultsIndexRoute =
  AppSensitiveProtectionResultsIndexRouteImport.update({
    id: '/sensitive-protection/results/',
    path: '/sensitive-protection/results/',
    getParentRoute: () => AppRoute,
  } as any)
const ApiPublicHooksScanOrchestratorRoute =
  ApiPublicHooksScanOrchestratorRouteImport.update({
    id: '/api/public/hooks/scan-orchestrator',
    path: '/api/public/hooks/scan-orchestrator',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksResendWebhookRoute =
  ApiPublicHooksResendWebhookRouteImport.update({
    id: '/api/public/hooks/resend-webhook',
    path: '/api/public/hooks/resend-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksReleaseProtectionMonitorRoute =
  ApiPublicHooksReleaseProtectionMonitorRouteImport.update({
    id: '/api/public/hooks/release-protection-monitor',
    path: '/api/public/hooks/release-protection-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProtectionSchedulerTokenRoute =
  ApiPublicHooksProtectionSchedulerTokenRouteImport.update({
    id: '/api/public/hooks/protection-scheduler-token',
    path: '/api/public/hooks/protection-scheduler-token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProtectionAutopilotRoute =
  ApiPublicHooksProtectionAutopilotRouteImport.update({
    id: '/api/public/hooks/protection-autopilot',
    path: '/api/public/hooks/protection-autopilot',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksProtectionActivationRepairRoute =
  ApiPublicHooksProtectionActivationRepairRouteImport.update({
    id: '/api/public/hooks/protection-activation-repair',
    path: '/api/public/hooks/protection-activation-repair',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksPostmarkWebhookRoute =
  ApiPublicHooksPostmarkWebhookRouteImport.update({
    id: '/api/public/hooks/postmark-webhook',
    path: '/api/public/hooks/postmark-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksEnforcementWorkerRoute =
  ApiPublicHooksEnforcementWorkerRouteImport.update({
    id: '/api/public/hooks/enforcement-worker',
    path: '/api/public/hooks/enforcement-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDistributionMonitorRoute =
  ApiPublicHooksDistributionMonitorRouteImport.update({
    id: '/api/public/hooks/distribution-monitor',
    path: '/api/public/hooks/distribution-monitor',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeepfakeScanExecuteRoute =
  ApiPublicHooksDeepfakeScanExecuteRouteImport.update({
    id: '/api/public/hooks/deepfake-scan-execute',
    path: '/api/public/hooks/deepfake-scan-execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeepfakeManualEvidenceExecuteRoute =
  ApiPublicHooksDeepfakeManualEvidenceExecuteRouteImport.update({
    id: '/api/public/hooks/deepfake-manual-evidence-execute',
    path: '/api/public/hooks/deepfake-manual-evidence-execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeepfakeGoogleImagesWorkerRoute =
  ApiPublicHooksDeepfakeGoogleImagesWorkerRouteImport.update({
    id: '/api/public/hooks/deepfake-google-images-worker',
    path: '/api/public/hooks/deepfake-google-images-worker',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksCopyrightScanExecuteRoute =
  ApiPublicHooksCopyrightScanExecuteRouteImport.update({
    id: '/api/public/hooks/copyright-scan-execute',
    path: '/api/public/hooks/copyright-scan-execute',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksChannelWatchPollRoute =
  ApiPublicHooksChannelWatchPollRouteImport.update({
    id: '/api/public/hooks/channel-watch-poll',
    path: '/api/public/hooks/channel-watch-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationStatusRoute =
  ApiPublicHooksAutomationStatusRouteImport.update({
    id: '/api/public/hooks/automation-status',
    path: '/api/public/hooks/automation-status',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAutomationFetchRoute =
  ApiPublicHooksAutomationFetchRouteImport.update({
    id: '/api/public/hooks/automation-fetch',
    path: '/api/public/hooks/automation-fetch',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksApprovedSourcesPollRoute =
  ApiPublicHooksApprovedSourcesPollRouteImport.update({
    id: '/api/public/hooks/approved-sources-poll',
    path: '/api/public/hooks/approved-sources-poll',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksAgentAssessmentsRoute =
  ApiPublicHooksAgentAssessmentsRouteImport.update({
    id: '/api/public/hooks/agent-assessments',
    path: '/api/public/hooks/agent-assessments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppSensitiveProtectionResultsIdRoute =
  AppSensitiveProtectionResultsIdRouteImport.update({
    id: '/sensitive-protection/results/$id',
    path: '/sensitive-protection/results/$id',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/agent': typeof AgentRoute
  '/agent-admin': typeof AgentAdminRoute
  '/agent-assessment': typeof AgentAssessmentRoute
  '/auth': typeof AuthRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/identity-response-observatory': typeof IdentityResponseObservatoryRoute
  '/methodology': typeof MethodologyRoute
  '/newsroom': typeof NewsroomRoute
  '/onboarding': typeof OnboardingRoute
  '/partner-apply': typeof PartnerApplyRoute
  '/partner-status': typeof PartnerStatusRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/waitinglist': typeof WaitinglistRoute
  '/assets': typeof AppAssetsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/cases': typeof AppCasesRoute
  '/channel-watch': typeof AppChannelWatchRoute
  '/copyright-intel': typeof AppCopyrightIntelRoute
  '/dashboard': typeof AppDashboardRoute
  '/deepfake-intel': typeof AppDeepfakeIntelRoute
  '/enforcement': typeof AppEnforcementRoute
  '/evidence-vault': typeof AppEvidenceVaultRoute
  '/face-protection': typeof AppFaceProtectionRoute
  '/face-references': typeof AppFaceReferencesRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/narrative-intelligence': typeof AppNarrativeIntelligenceRoute
  '/notifications': typeof AppNotificationsRoute
  '/removals': typeof AppRemovalsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/threat-monitoring': typeof AppThreatMonitoringRoute
  '/threat-radar': typeof AppThreatRadarRoute
  '/youtube-removal': typeof AppYoutubeRemovalRoute
  '/partner': typeof PartnerPartnerRouteWithChildren
  '/api/scan': typeof ApiScanRoute
  '/face-handoff/$token': typeof FaceHandoffTokenRoute
  '/newsroom/deepfake-verification-guide': typeof NewsroomDeepfakeVerificationGuideRoute
  '/newsroom/executive-first-hour-playbook': typeof NewsroomExecutiveFirstHourPlaybookRoute
  '/newsroom/impersonation-response-guide': typeof NewsroomImpersonationResponseGuideRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/admin/approved-sources-review': typeof AppAdminApprovedSourcesReviewRoute
  '/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/admin/identity-review': typeof AppAdminIdentityReviewRoute
  '/admin/invites': typeof AppAdminInvitesRoute
  '/admin/multimedia-health': typeof AppAdminMultimediaHealthRoute
  '/admin/onboarding-reviews': typeof AppAdminOnboardingReviewsRoute
  '/admin/provider-activation': typeof AppAdminProviderActivationRoute
  '/admin/removal-routes': typeof AppAdminRemovalRoutesRoute
  '/admin/sensitive-protection': typeof AppAdminSensitiveProtectionRoute
  '/admin/waitlist': typeof AppAdminWaitlistRoute
  '/protection/sources': typeof AppProtectionSourcesRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/sensitive-protection/emergency': typeof AppSensitiveProtectionEmergencyRoute
  '/sensitive-protection/removal-cases': typeof AppSensitiveProtectionRemovalCasesRoute
  '/partner/clients': typeof PartnerPartnerClientsRoute
  '/partner/commissions': typeof PartnerPartnerCommissionsRoute
  '/partner/marketing': typeof PartnerPartnerMarketingRoute
  '/partner/payments': typeof PartnerPartnerPaymentsRoute
  '/partner/proposals': typeof PartnerPartnerProposalsRoute
  '/api/media/preview': typeof ApiMediaPreviewRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
  '/api/public/onboarding-completion-backfill': typeof ApiPublicOnboardingCompletionBackfillRoute
  '/api/public/veriff-webhook': typeof ApiPublicVeriffWebhookRoute
  '/sensitive-protection/': typeof AppSensitiveProtectionIndexRoute
  '/partner/': typeof PartnerPartnerIndexRoute
  '/sensitive-protection/results/$id': typeof AppSensitiveProtectionResultsIdRoute
  '/api/public/hooks/agent-assessments': typeof ApiPublicHooksAgentAssessmentsRoute
  '/api/public/hooks/approved-sources-poll': typeof ApiPublicHooksApprovedSourcesPollRoute
  '/api/public/hooks/automation-fetch': typeof ApiPublicHooksAutomationFetchRoute
  '/api/public/hooks/automation-status': typeof ApiPublicHooksAutomationStatusRoute
  '/api/public/hooks/channel-watch-poll': typeof ApiPublicHooksChannelWatchPollRoute
  '/api/public/hooks/copyright-scan-execute': typeof ApiPublicHooksCopyrightScanExecuteRoute
  '/api/public/hooks/deepfake-google-images-worker': typeof ApiPublicHooksDeepfakeGoogleImagesWorkerRoute
  '/api/public/hooks/deepfake-manual-evidence-execute': typeof ApiPublicHooksDeepfakeManualEvidenceExecuteRoute
  '/api/public/hooks/deepfake-scan-execute': typeof ApiPublicHooksDeepfakeScanExecuteRoute
  '/api/public/hooks/distribution-monitor': typeof ApiPublicHooksDistributionMonitorRoute
  '/api/public/hooks/enforcement-worker': typeof ApiPublicHooksEnforcementWorkerRoute
  '/api/public/hooks/postmark-webhook': typeof ApiPublicHooksPostmarkWebhookRoute
  '/api/public/hooks/protection-activation-repair': typeof ApiPublicHooksProtectionActivationRepairRoute
  '/api/public/hooks/protection-autopilot': typeof ApiPublicHooksProtectionAutopilotRoute
  '/api/public/hooks/protection-scheduler-token': typeof ApiPublicHooksProtectionSchedulerTokenRoute
  '/api/public/hooks/release-protection-monitor': typeof ApiPublicHooksReleaseProtectionMonitorRoute
  '/api/public/hooks/resend-webhook': typeof ApiPublicHooksResendWebhookRoute
  '/api/public/hooks/scan-orchestrator': typeof ApiPublicHooksScanOrchestratorRoute
  '/sensitive-protection/results/': typeof AppSensitiveProtectionResultsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/agent': typeof AgentRoute
  '/agent-admin': typeof AgentAdminRoute
  '/agent-assessment': typeof AgentAssessmentRoute
  '/auth': typeof AuthRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/identity-response-observatory': typeof IdentityResponseObservatoryRoute
  '/methodology': typeof MethodologyRoute
  '/newsroom': typeof NewsroomRoute
  '/onboarding': typeof OnboardingRoute
  '/partner-apply': typeof PartnerApplyRoute
  '/partner-status': typeof PartnerStatusRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/waitinglist': typeof WaitinglistRoute
  '/assets': typeof AppAssetsRoute
  '/campaigns': typeof AppCampaignsRoute
  '/cases': typeof AppCasesRoute
  '/channel-watch': typeof AppChannelWatchRoute
  '/copyright-intel': typeof AppCopyrightIntelRoute
  '/dashboard': typeof AppDashboardRoute
  '/deepfake-intel': typeof AppDeepfakeIntelRoute
  '/enforcement': typeof AppEnforcementRoute
  '/evidence-vault': typeof AppEvidenceVaultRoute
  '/face-protection': typeof AppFaceProtectionRoute
  '/face-references': typeof AppFaceReferencesRoute
  '/intelligence': typeof AppIntelligenceRoute
  '/narrative-intelligence': typeof AppNarrativeIntelligenceRoute
  '/notifications': typeof AppNotificationsRoute
  '/removals': typeof AppRemovalsRoute
  '/reports': typeof AppReportsRouteWithChildren
  '/scan': typeof AppScanRoute
  '/settings': typeof AppSettingsRoute
  '/threat-monitoring': typeof AppThreatMonitoringRoute
  '/threat-radar': typeof AppThreatRadarRoute
  '/youtube-removal': typeof AppYoutubeRemovalRoute
  '/api/scan': typeof ApiScanRoute
  '/face-handoff/$token': typeof FaceHandoffTokenRoute
  '/newsroom/deepfake-verification-guide': typeof NewsroomDeepfakeVerificationGuideRoute
  '/newsroom/executive-first-hour-playbook': typeof NewsroomExecutiveFirstHourPlaybookRoute
  '/newsroom/impersonation-response-guide': typeof NewsroomImpersonationResponseGuideRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/admin/approved-sources-review': typeof AppAdminApprovedSourcesReviewRoute
  '/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/admin/identity-review': typeof AppAdminIdentityReviewRoute
  '/admin/invites': typeof AppAdminInvitesRoute
  '/admin/multimedia-health': typeof AppAdminMultimediaHealthRoute
  '/admin/onboarding-reviews': typeof AppAdminOnboardingReviewsRoute
  '/admin/provider-activation': typeof AppAdminProviderActivationRoute
  '/admin/removal-routes': typeof AppAdminRemovalRoutesRoute
  '/admin/sensitive-protection': typeof AppAdminSensitiveProtectionRoute
  '/admin/waitlist': typeof AppAdminWaitlistRoute
  '/protection/sources': typeof AppProtectionSourcesRoute
  '/reports/$reportId': typeof AppReportsReportIdRoute
  '/sensitive-protection/emergency': typeof AppSensitiveProtectionEmergencyRoute
  '/sensitive-protection/removal-cases': typeof AppSensitiveProtectionRemovalCasesRoute
  '/partner/clients': typeof PartnerPartnerClientsRoute
  '/partner/commissions': typeof PartnerPartnerCommissionsRoute
  '/partner/marketing': typeof PartnerPartnerMarketingRoute
  '/partner/payments': typeof PartnerPartnerPaymentsRoute
  '/partner/proposals': typeof PartnerPartnerProposalsRoute
  '/api/media/preview': typeof ApiMediaPreviewRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
  '/api/public/onboarding-completion-backfill': typeof ApiPublicOnboardingCompletionBackfillRoute
  '/api/public/veriff-webhook': typeof ApiPublicVeriffWebhookRoute
  '/sensitive-protection': typeof AppSensitiveProtectionIndexRoute
  '/partner': typeof PartnerPartnerIndexRoute
  '/sensitive-protection/results/$id': typeof AppSensitiveProtectionResultsIdRoute
  '/api/public/hooks/agent-assessments': typeof ApiPublicHooksAgentAssessmentsRoute
  '/api/public/hooks/approved-sources-poll': typeof ApiPublicHooksApprovedSourcesPollRoute
  '/api/public/hooks/automation-fetch': typeof ApiPublicHooksAutomationFetchRoute
  '/api/public/hooks/automation-status': typeof ApiPublicHooksAutomationStatusRoute
  '/api/public/hooks/channel-watch-poll': typeof ApiPublicHooksChannelWatchPollRoute
  '/api/public/hooks/copyright-scan-execute': typeof ApiPublicHooksCopyrightScanExecuteRoute
  '/api/public/hooks/deepfake-google-images-worker': typeof ApiPublicHooksDeepfakeGoogleImagesWorkerRoute
  '/api/public/hooks/deepfake-manual-evidence-execute': typeof ApiPublicHooksDeepfakeManualEvidenceExecuteRoute
  '/api/public/hooks/deepfake-scan-execute': typeof ApiPublicHooksDeepfakeScanExecuteRoute
  '/api/public/hooks/distribution-monitor': typeof ApiPublicHooksDistributionMonitorRoute
  '/api/public/hooks/enforcement-worker': typeof ApiPublicHooksEnforcementWorkerRoute
  '/api/public/hooks/postmark-webhook': typeof ApiPublicHooksPostmarkWebhookRoute
  '/api/public/hooks/protection-activation-repair': typeof ApiPublicHooksProtectionActivationRepairRoute
  '/api/public/hooks/protection-autopilot': typeof ApiPublicHooksProtectionAutopilotRoute
  '/api/public/hooks/protection-scheduler-token': typeof ApiPublicHooksProtectionSchedulerTokenRoute
  '/api/public/hooks/release-protection-monitor': typeof ApiPublicHooksReleaseProtectionMonitorRoute
  '/api/public/hooks/resend-webhook': typeof ApiPublicHooksResendWebhookRoute
  '/api/public/hooks/scan-orchestrator': typeof ApiPublicHooksScanOrchestratorRoute
  '/sensitive-protection/results': typeof AppSensitiveProtectionResultsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_partner': typeof PartnerRouteWithChildren
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/agent': typeof AgentRoute
  '/agent-admin': typeof AgentAdminRoute
  '/agent-assessment': typeof AgentAssessmentRoute
  '/auth': typeof AuthRoute
  '/case-studies': typeof CaseStudiesRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/identity-response-observatory': typeof IdentityResponseObservatoryRoute
  '/methodology': typeof MethodologyRoute
  '/newsroom': typeof NewsroomRoute
  '/onboarding': typeof OnboardingRoute
  '/partner-apply': typeof PartnerApplyRoute
  '/partner-status': typeof PartnerStatusRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/terms': typeof TermsRoute
  '/waitinglist': typeof WaitinglistRoute
  '/_app/assets': typeof AppAssetsRoute
  '/_app/campaigns': typeof AppCampaignsRoute
  '/_app/cases': typeof AppCasesRoute
  '/_app/channel-watch': typeof AppChannelWatchRoute
  '/_app/copyright-intel': typeof AppCopyrightIntelRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/deepfake-intel': typeof AppDeepfakeIntelRoute
  '/_app/enforcement': typeof AppEnforcementRoute
  '/_app/evidence-vault': typeof AppEvidenceVaultRoute
  '/_app/face-protection': typeof AppFaceProtectionRoute
  '/_app/face-references': typeof AppFaceReferencesRoute
  '/_app/intelligence': typeof AppIntelligenceRoute
  '/_app/narrative-intelligence': typeof AppNarrativeIntelligenceRoute
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/removals': typeof AppRemovalsRoute
  '/_app/reports': typeof AppReportsRouteWithChildren
  '/_app/scan': typeof AppScanRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/threat-monitoring': typeof AppThreatMonitoringRoute
  '/_app/threat-radar': typeof AppThreatRadarRoute
  '/_app/youtube-removal': typeof AppYoutubeRemovalRoute
  '/_partner/partner': typeof PartnerPartnerRouteWithChildren
  '/api/scan': typeof ApiScanRoute
  '/face-handoff/$token': typeof FaceHandoffTokenRoute
  '/newsroom_/deepfake-verification-guide': typeof NewsroomDeepfakeVerificationGuideRoute
  '/newsroom_/executive-first-hour-playbook': typeof NewsroomExecutiveFirstHourPlaybookRoute
  '/newsroom_/impersonation-response-guide': typeof NewsroomImpersonationResponseGuideRoute
  '/verify/$slug': typeof VerifySlugRoute
  '/_app/admin/approved-sources-review': typeof AppAdminApprovedSourcesReviewRoute
  '/_app/admin/diagnostics': typeof AppAdminDiagnosticsRoute
  '/_app/admin/identity-review': typeof AppAdminIdentityReviewRoute
  '/_app/admin/invites': typeof AppAdminInvitesRoute
  '/_app/admin/multimedia-health': typeof AppAdminMultimediaHealthRoute
  '/_app/admin/onboarding-reviews': typeof AppAdminOnboardingReviewsRoute
  '/_app/admin/provider-activation': typeof AppAdminProviderActivationRoute
  '/_app/admin/removal-routes': typeof AppAdminRemovalRoutesRoute
  '/_app/admin/sensitive-protection': typeof AppAdminSensitiveProtectionRoute
  '/_app/admin/waitlist': typeof AppAdminWaitlistRoute
  '/_app/protection/sources': typeof AppProtectionSourcesRoute
  '/_app/reports/$reportId': typeof AppReportsReportIdRoute
  '/_app/sensitive-protection/emergency': typeof AppSensitiveProtectionEmergencyRoute
  '/_app/sensitive-protection/removal-cases': typeof AppSensitiveProtectionRemovalCasesRoute
  '/_partner/partner/clients': typeof PartnerPartnerClientsRoute
  '/_partner/partner/commissions': typeof PartnerPartnerCommissionsRoute
  '/_partner/partner/marketing': typeof PartnerPartnerMarketingRoute
  '/_partner/partner/payments': typeof PartnerPartnerPaymentsRoute
  '/_partner/partner/proposals': typeof PartnerPartnerProposalsRoute
  '/api/media/preview': typeof ApiMediaPreviewRoute
  '/api/public/image-proxy': typeof ApiPublicImageProxyRoute
  '/api/public/onboarding-completion-backfill': typeof ApiPublicOnboardingCompletionBackfillRoute
  '/api/public/veriff-webhook': typeof ApiPublicVeriffWebhookRoute
  '/_app/sensitive-protection/': typeof AppSensitiveProtectionIndexRoute
  '/_partner/partner/': typeof PartnerPartnerIndexRoute
  '/_app/sensitive-protection/results/$id': typeof AppSensitiveProtectionResultsIdRoute
  '/api/public/hooks/agent-assessments': typeof ApiPublicHooksAgentAssessmentsRoute
  '/api/public/hooks/approved-sources-poll': typeof ApiPublicHooksApprovedSourcesPollRoute
  '/api/public/hooks/automation-fetch': typeof ApiPublicHooksAutomationFetchRoute
  '/api/public/hooks/automation-status': typeof ApiPublicHooksAutomationStatusRoute
  '/api/public/hooks/channel-watch-poll': typeof ApiPublicHooksChannelWatchPollRoute
  '/api/public/hooks/copyright-scan-execute': typeof ApiPublicHooksCopyrightScanExecuteRoute
  '/api/public/hooks/deepfake-google-images-worker': typeof ApiPublicHooksDeepfakeGoogleImagesWorkerRoute
  '/api/public/hooks/deepfake-manual-evidence-execute': typeof ApiPublicHooksDeepfakeManualEvidenceExecuteRoute
  '/api/public/hooks/deepfake-scan-execute': typeof ApiPublicHooksDeepfakeScanExecuteRoute
  '/api/public/hooks/distribution-monitor': typeof ApiPublicHooksDistributionMonitorRoute
  '/api/public/hooks/enforcement-worker': typeof ApiPublicHooksEnforcementWorkerRoute
  '/api/public/hooks/postmark-webhook': typeof ApiPublicHooksPostmarkWebhookRoute
  '/api/public/hooks/protection-activation-repair': typeof ApiPublicHooksProtectionActivationRepairRoute
  '/api/public/hooks/protection-autopilot': typeof ApiPublicHooksProtectionAutopilotRoute
  '/api/public/hooks/protection-scheduler-token': typeof ApiPublicHooksProtectionSchedulerTokenRoute
  '/api/public/hooks/release-protection-monitor': typeof ApiPublicHooksReleaseProtectionMonitorRoute
  '/api/public/hooks/resend-webhook': typeof ApiPublicHooksResendWebhookRoute
  '/api/public/hooks/scan-orchestrator': typeof ApiPublicHooksScanOrchestratorRoute
  '/_app/sensitive-protection/results/': typeof AppSensitiveProtectionResultsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/agent'
    | '/agent-admin'
    | '/agent-assessment'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/identity-response-observatory'
    | '/methodology'
    | '/newsroom'
    | '/onboarding'
    | '/partner-apply'
    | '/partner-status'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/waitinglist'
    | '/assets'
    | '/campaigns'
    | '/cases'
    | '/channel-watch'
    | '/copyright-intel'
    | '/dashboard'
    | '/deepfake-intel'
    | '/enforcement'
    | '/evidence-vault'
    | '/face-protection'
    | '/face-references'
    | '/intelligence'
    | '/narrative-intelligence'
    | '/notifications'
    | '/removals'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/threat-monitoring'
    | '/threat-radar'
    | '/youtube-removal'
    | '/partner'
    | '/api/scan'
    | '/face-handoff/$token'
    | '/newsroom/deepfake-verification-guide'
    | '/newsroom/executive-first-hour-playbook'
    | '/newsroom/impersonation-response-guide'
    | '/verify/$slug'
    | '/admin/approved-sources-review'
    | '/admin/diagnostics'
    | '/admin/identity-review'
    | '/admin/invites'
    | '/admin/multimedia-health'
    | '/admin/onboarding-reviews'
    | '/admin/provider-activation'
    | '/admin/removal-routes'
    | '/admin/sensitive-protection'
    | '/admin/waitlist'
    | '/protection/sources'
    | '/reports/$reportId'
    | '/sensitive-protection/emergency'
    | '/sensitive-protection/removal-cases'
    | '/partner/clients'
    | '/partner/commissions'
    | '/partner/marketing'
    | '/partner/payments'
    | '/partner/proposals'
    | '/api/media/preview'
    | '/api/public/image-proxy'
    | '/api/public/onboarding-completion-backfill'
    | '/api/public/veriff-webhook'
    | '/sensitive-protection/'
    | '/partner/'
    | '/sensitive-protection/results/$id'
    | '/api/public/hooks/agent-assessments'
    | '/api/public/hooks/approved-sources-poll'
    | '/api/public/hooks/automation-fetch'
    | '/api/public/hooks/automation-status'
    | '/api/public/hooks/channel-watch-poll'
    | '/api/public/hooks/copyright-scan-execute'
    | '/api/public/hooks/deepfake-google-images-worker'
    | '/api/public/hooks/deepfake-manual-evidence-execute'
    | '/api/public/hooks/deepfake-scan-execute'
    | '/api/public/hooks/distribution-monitor'
    | '/api/public/hooks/enforcement-worker'
    | '/api/public/hooks/postmark-webhook'
    | '/api/public/hooks/protection-activation-repair'
    | '/api/public/hooks/protection-autopilot'
    | '/api/public/hooks/protection-scheduler-token'
    | '/api/public/hooks/release-protection-monitor'
    | '/api/public/hooks/resend-webhook'
    | '/api/public/hooks/scan-orchestrator'
    | '/sensitive-protection/results/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/agent'
    | '/agent-admin'
    | '/agent-assessment'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/identity-response-observatory'
    | '/methodology'
    | '/newsroom'
    | '/onboarding'
    | '/partner-apply'
    | '/partner-status'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/waitinglist'
    | '/assets'
    | '/campaigns'
    | '/cases'
    | '/channel-watch'
    | '/copyright-intel'
    | '/dashboard'
    | '/deepfake-intel'
    | '/enforcement'
    | '/evidence-vault'
    | '/face-protection'
    | '/face-references'
    | '/intelligence'
    | '/narrative-intelligence'
    | '/notifications'
    | '/removals'
    | '/reports'
    | '/scan'
    | '/settings'
    | '/threat-monitoring'
    | '/threat-radar'
    | '/youtube-removal'
    | '/api/scan'
    | '/face-handoff/$token'
    | '/newsroom/deepfake-verification-guide'
    | '/newsroom/executive-first-hour-playbook'
    | '/newsroom/impersonation-response-guide'
    | '/verify/$slug'
    | '/admin/approved-sources-review'
    | '/admin/diagnostics'
    | '/admin/identity-review'
    | '/admin/invites'
    | '/admin/multimedia-health'
    | '/admin/onboarding-reviews'
    | '/admin/provider-activation'
    | '/admin/removal-routes'
    | '/admin/sensitive-protection'
    | '/admin/waitlist'
    | '/protection/sources'
    | '/reports/$reportId'
    | '/sensitive-protection/emergency'
    | '/sensitive-protection/removal-cases'
    | '/partner/clients'
    | '/partner/commissions'
    | '/partner/marketing'
    | '/partner/payments'
    | '/partner/proposals'
    | '/api/media/preview'
    | '/api/public/image-proxy'
    | '/api/public/onboarding-completion-backfill'
    | '/api/public/veriff-webhook'
    | '/sensitive-protection'
    | '/partner'
    | '/sensitive-protection/results/$id'
    | '/api/public/hooks/agent-assessments'
    | '/api/public/hooks/approved-sources-poll'
    | '/api/public/hooks/automation-fetch'
    | '/api/public/hooks/automation-status'
    | '/api/public/hooks/channel-watch-poll'
    | '/api/public/hooks/copyright-scan-execute'
    | '/api/public/hooks/deepfake-google-images-worker'
    | '/api/public/hooks/deepfake-manual-evidence-execute'
    | '/api/public/hooks/deepfake-scan-execute'
    | '/api/public/hooks/distribution-monitor'
    | '/api/public/hooks/enforcement-worker'
    | '/api/public/hooks/postmark-webhook'
    | '/api/public/hooks/protection-activation-repair'
    | '/api/public/hooks/protection-autopilot'
    | '/api/public/hooks/protection-scheduler-token'
    | '/api/public/hooks/release-protection-monitor'
    | '/api/public/hooks/resend-webhook'
    | '/api/public/hooks/scan-orchestrator'
    | '/sensitive-protection/results'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_partner'
    | '/about'
    | '/acceptable-use'
    | '/agent'
    | '/agent-admin'
    | '/agent-assessment'
    | '/auth'
    | '/case-studies'
    | '/contact'
    | '/cookies'
    | '/identity-response-observatory'
    | '/methodology'
    | '/newsroom'
    | '/onboarding'
    | '/partner-apply'
    | '/partner-status'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/waitinglist'
    | '/_app/assets'
    | '/_app/campaigns'
    | '/_app/cases'
    | '/_app/channel-watch'
    | '/_app/copyright-intel'
    | '/_app/dashboard'
    | '/_app/deepfake-intel'
    | '/_app/enforcement'
    | '/_app/evidence-vault'
    | '/_app/face-protection'
    | '/_app/face-references'
    | '/_app/intelligence'
    | '/_app/narrative-intelligence'
    | '/_app/notifications'
    | '/_app/removals'
    | '/_app/reports'
    | '/_app/scan'
    | '/_app/settings'
    | '/_app/threat-monitoring'
    | '/_app/threat-radar'
    | '/_app/youtube-removal'
    | '/_partner/partner'
    | '/api/scan'
    | '/face-handoff/$token'
    | '/newsroom_/deepfake-verification-guide'
    | '/newsroom_/executive-first-hour-playbook'
    | '/newsroom_/impersonation-response-guide'
    | '/verify/$slug'
    | '/_app/admin/approved-sources-review'
    | '/_app/admin/diagnostics'
    | '/_app/admin/identity-review'
    | '/_app/admin/invites'
    | '/_app/admin/multimedia-health'
    | '/_app/admin/onboarding-reviews'
    | '/_app/admin/provider-activation'
    | '/_app/admin/removal-routes'
    | '/_app/admin/sensitive-protection'
    | '/_app/admin/waitlist'
    | '/_app/protection/sources'
    | '/_app/reports/$reportId'
    | '/_app/sensitive-protection/emergency'
    | '/_app/sensitive-protection/removal-cases'
    | '/_partner/partner/clients'
    | '/_partner/partner/commissions'
    | '/_partner/partner/marketing'
    | '/_partner/partner/payments'
    | '/_partner/partner/proposals'
    | '/api/media/preview'
    | '/api/public/image-proxy'
    | '/api/public/onboarding-completion-backfill'
    | '/api/public/veriff-webhook'
    | '/_app/sensitive-protection/'
    | '/_partner/partner/'
    | '/_app/sensitive-protection/results/$id'
    | '/api/public/hooks/agent-assessments'
    | '/api/public/hooks/approved-sources-poll'
    | '/api/public/hooks/automation-fetch'
    | '/api/public/hooks/automation-status'
    | '/api/public/hooks/channel-watch-poll'
    | '/api/public/hooks/copyright-scan-execute'
    | '/api/public/hooks/deepfake-google-images-worker'
    | '/api/public/hooks/deepfake-manual-evidence-execute'
    | '/api/public/hooks/deepfake-scan-execute'
    | '/api/public/hooks/distribution-monitor'
    | '/api/public/hooks/enforcement-worker'
    | '/api/public/hooks/postmark-webhook'
    | '/api/public/hooks/protection-activation-repair'
    | '/api/public/hooks/protection-autopilot'
    | '/api/public/hooks/protection-scheduler-token'
    | '/api/public/hooks/release-protection-monitor'
    | '/api/public/hooks/resend-webhook'
    | '/api/public/hooks/scan-orchestrator'
    | '/_app/sensitive-protection/results/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  PartnerRoute: typeof PartnerRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AgentRoute: typeof AgentRoute
  AgentAdminRoute: typeof AgentAdminRoute
  AgentAssessmentRoute: typeof AgentAssessmentRoute
  AuthRoute: typeof AuthRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  IdentityResponseObservatoryRoute: typeof IdentityResponseObservatoryRoute
  MethodologyRoute: typeof MethodologyRoute
  NewsroomRoute: typeof NewsroomRoute
  OnboardingRoute: typeof OnboardingRoute
  PartnerApplyRoute: typeof PartnerApplyRoute
  PartnerStatusRoute: typeof PartnerStatusRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  TermsRoute: typeof TermsRoute
  WaitinglistRoute: typeof WaitinglistRoute
  ApiScanRoute: typeof ApiScanRoute
  FaceHandoffTokenRoute: typeof FaceHandoffTokenRoute
  NewsroomDeepfakeVerificationGuideRoute: typeof NewsroomDeepfakeVerificationGuideRoute
  NewsroomExecutiveFirstHourPlaybookRoute: typeof NewsroomExecutiveFirstHourPlaybookRoute
  NewsroomImpersonationResponseGuideRoute: typeof NewsroomImpersonationResponseGuideRoute
  VerifySlugRoute: typeof VerifySlugRoute
  ApiMediaPreviewRoute: typeof ApiMediaPreviewRoute
  ApiPublicImageProxyRoute: typeof ApiPublicImageProxyRoute
  ApiPublicOnboardingCompletionBackfillRoute: typeof ApiPublicOnboardingCompletionBackfillRoute
  ApiPublicVeriffWebhookRoute: typeof ApiPublicVeriffWebhookRoute
  ApiPublicHooksAgentAssessmentsRoute: typeof ApiPublicHooksAgentAssessmentsRoute
  ApiPublicHooksApprovedSourcesPollRoute: typeof ApiPublicHooksApprovedSourcesPollRoute
  ApiPublicHooksAutomationFetchRoute: typeof ApiPublicHooksAutomationFetchRoute
  ApiPublicHooksAutomationStatusRoute: typeof ApiPublicHooksAutomationStatusRoute
  ApiPublicHooksChannelWatchPollRoute: typeof ApiPublicHooksChannelWatchPollRoute
  ApiPublicHooksCopyrightScanExecuteRoute: typeof ApiPublicHooksCopyrightScanExecuteRoute
  ApiPublicHooksDeepfakeGoogleImagesWorkerRoute: typeof ApiPublicHooksDeepfakeGoogleImagesWorkerRoute
  ApiPublicHooksDeepfakeManualEvidenceExecuteRoute: typeof ApiPublicHooksDeepfakeManualEvidenceExecuteRoute
  ApiPublicHooksDeepfakeScanExecuteRoute: typeof ApiPublicHooksDeepfakeScanExecuteRoute
  ApiPublicHooksDistributionMonitorRoute: typeof ApiPublicHooksDistributionMonitorRoute
  ApiPublicHooksEnforcementWorkerRoute: typeof ApiPublicHooksEnforcementWorkerRoute
  ApiPublicHooksPostmarkWebhookRoute: typeof ApiPublicHooksPostmarkWebhookRoute
  ApiPublicHooksProtectionActivationRepairRoute: typeof ApiPublicHooksProtectionActivationRepairRoute
  ApiPublicHooksProtectionAutopilotRoute: typeof ApiPublicHooksProtectionAutopilotRoute
  ApiPublicHooksProtectionSchedulerTokenRoute: typeof ApiPublicHooksProtectionSchedulerTokenRoute
  ApiPublicHooksReleaseProtectionMonitorRoute: typeof ApiPublicHooksReleaseProtectionMonitorRoute
  ApiPublicHooksResendWebhookRoute: typeof ApiPublicHooksResendWebhookRoute
  ApiPublicHooksScanOrchestratorRoute: typeof ApiPublicHooksScanOrchestratorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitinglist': {
      id: '/waitinglist'
      path: '/waitinglist'
      fullPath: '/waitinglist'
      preLoaderRoute: typeof WaitinglistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-status': {
      id: '/partner-status'
      path: '/partner-status'
      fullPath: '/partner-status'
      preLoaderRoute: typeof PartnerStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner-apply': {
      id: '/partner-apply'
      path: '/partner-apply'
      fullPath: '/partner-apply'
      preLoaderRoute: typeof PartnerApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom': {
      id: '/newsroom'
      path: '/newsroom'
      fullPath: '/newsroom'
      preLoaderRoute: typeof NewsroomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/identity-response-observatory': {
      id: '/identity-response-observatory'
      path: '/identity-response-observatory'
      fullPath: '/identity-response-observatory'
      preLoaderRoute: typeof IdentityResponseObservatoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-assessment': {
      id: '/agent-assessment'
      path: '/agent-assessment'
      fullPath: '/agent-assessment'
      preLoaderRoute: typeof AgentAssessmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-admin': {
      id: '/agent-admin'
      path: '/agent-admin'
      fullPath: '/agent-admin'
      preLoaderRoute: typeof AgentAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent': {
      id: '/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AgentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_partner': {
      id: '/_partner'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify/$slug': {
      id: '/verify/$slug'
      path: '/verify/$slug'
      fullPath: '/verify/$slug'
      preLoaderRoute: typeof VerifySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom_/impersonation-response-guide': {
      id: '/newsroom_/impersonation-response-guide'
      path: '/newsroom/impersonation-response-guide'
      fullPath: '/newsroom/impersonation-response-guide'
      preLoaderRoute: typeof NewsroomImpersonationResponseGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom_/executive-first-hour-playbook': {
      id: '/newsroom_/executive-first-hour-playbook'
      path: '/newsroom/executive-first-hour-playbook'
      fullPath: '/newsroom/executive-first-hour-playbook'
      preLoaderRoute: typeof NewsroomExecutiveFirstHourPlaybookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsroom_/deepfake-verification-guide': {
      id: '/newsroom_/deepfake-verification-guide'
      path: '/newsroom/deepfake-verification-guide'
      fullPath: '/newsroom/deepfake-verification-guide'
      preLoaderRoute: typeof NewsroomDeepfakeVerificationGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/face-handoff/$token': {
      id: '/face-handoff/$token'
      path: '/face-handoff/$token'
      fullPath: '/face-handoff/$token'
      preLoaderRoute: typeof FaceHandoffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_partner/partner': {
      id: '/_partner/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerPartnerRouteImport
      parentRoute: typeof PartnerRoute
    }
    '/_app/youtube-removal': {
      id: '/_app/youtube-removal'
      path: '/youtube-removal'
      fullPath: '/youtube-removal'
      preLoaderRoute: typeof AppYoutubeRemovalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threat-radar': {
      id: '/_app/threat-radar'
      path: '/threat-radar'
      fullPath: '/threat-radar'
      preLoaderRoute: typeof AppThreatRadarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/threat-monitoring': {
      id: '/_app/threat-monitoring'
      path: '/threat-monitoring'
      fullPath: '/threat-monitoring'
      preLoaderRoute: typeof AppThreatMonitoringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scan': {
      id: '/_app/scan'
      path: '/scan'
      fullPath: '/scan'
      preLoaderRoute: typeof AppScanRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/removals': {
      id: '/_app/removals'
      path: '/removals'
      fullPath: '/removals'
      preLoaderRoute: typeof AppRemovalsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/narrative-intelligence': {
      id: '/_app/narrative-intelligence'
      path: '/narrative-intelligence'
      fullPath: '/narrative-intelligence'
      preLoaderRoute: typeof AppNarrativeIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/intelligence': {
      id: '/_app/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof AppIntelligenceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/face-references': {
      id: '/_app/face-references'
      path: '/face-references'
      fullPath: '/face-references'
      preLoaderRoute: typeof AppFaceReferencesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/face-protection': {
      id: '/_app/face-protection'
      path: '/face-protection'
      fullPath: '/face-protection'
      preLoaderRoute: typeof AppFaceProtectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/evidence-vault': {
      id: '/_app/evidence-vault'
      path: '/evidence-vault'
      fullPath: '/evidence-vault'
      preLoaderRoute: typeof AppEvidenceVaultRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/enforcement': {
      id: '/_app/enforcement'
      path: '/enforcement'
      fullPath: '/enforcement'
      preLoaderRoute: typeof AppEnforcementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/deepfake-intel': {
      id: '/_app/deepfake-intel'
      path: '/deepfake-intel'
      fullPath: '/deepfake-intel'
      preLoaderRoute: typeof AppDeepfakeIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/copyright-intel': {
      id: '/_app/copyright-intel'
      path: '/copyright-intel'
      fullPath: '/copyright-intel'
      preLoaderRoute: typeof AppCopyrightIntelRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/channel-watch': {
      id: '/_app/channel-watch'
      path: '/channel-watch'
      fullPath: '/channel-watch'
      preLoaderRoute: typeof AppChannelWatchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cases': {
      id: '/_app/cases'
      path: '/cases'
      fullPath: '/cases'
      preLoaderRoute: typeof AppCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assets': {
      id: '/_app/assets'
      path: '/assets'
      fullPath: '/assets'
      preLoaderRoute: typeof AppAssetsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_partner/partner/': {
      id: '/_partner/partner/'
      path: '/'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerPartnerIndexRouteImport
      parentRoute: typeof PartnerPartnerRoute
    }
    '/_app/sensitive-protection/': {
      id: '/_app/sensitive-protection/'
      path: '/sensitive-protection'
      fullPath: '/sensitive-protection/'
      preLoaderRoute: typeof AppSensitiveProtectionIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/veriff-webhook': {
      id: '/api/public/veriff-webhook'
      path: '/api/public/veriff-webhook'
      fullPath: '/api/public/veriff-webhook'
      preLoaderRoute: typeof ApiPublicVeriffWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/onboarding-completion-backfill': {
      id: '/api/public/onboarding-completion-backfill'
      path: '/api/public/onboarding-completion-backfill'
      fullPath: '/api/public/onboarding-completion-backfill'
      preLoaderRoute: typeof ApiPublicOnboardingCompletionBackfillRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image-proxy': {
      id: '/api/public/image-proxy'
      path: '/api/public/image-proxy'
      fullPath: '/api/public/image-proxy'
      preLoaderRoute: typeof ApiPublicImageProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/media/preview': {
      id: '/api/media/preview'
      path: '/api/media/preview'
      fullPath: '/api/media/preview'
      preLoaderRoute: typeof ApiMediaPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_partner/partner/proposals': {
      id: '/_partner/partner/proposals'
      path: '/proposals'
      fullPath: '/partner/proposals'
      preLoaderRoute: typeof PartnerPartnerProposalsRouteImport
      parentRoute: typeof PartnerPartnerRoute
    }
    '/_partner/partner/payments': {
      id: '/_partner/partner/payments'
      path: '/payments'
      fullPath: '/partner/payments'
      preLoaderRoute: typeof PartnerPartnerPaymentsRouteImport
      parentRoute: typeof PartnerPartnerRoute
    }
    '/_partner/partner/marketing': {
      id: '/_partner/partner/marketing'
      path: '/marketing'
      fullPath: '/partner/marketing'
      preLoaderRoute: typeof PartnerPartnerMarketingRouteImport
      parentRoute: typeof PartnerPartnerRoute
    }
    '/_partner/partner/commissions': {
      id: '/_partner/partner/commissions'
      path: '/commissions'
      fullPath: '/partner/commissions'
      preLoaderRoute: typeof PartnerPartnerCommissionsRouteImport
      parentRoute: typeof PartnerPartnerRoute
    }
    '/_partner/partner/clients': {
      id: '/_partner/partner/clients'
      path: '/clients'
      fullPath: '/partner/clients'
      preLoaderRoute: typeof PartnerPartnerClientsRouteImport
      parentRoute: typeof PartnerPartnerRoute
    }
    '/_app/sensitive-protection/removal-cases': {
      id: '/_app/sensitive-protection/removal-cases'
      path: '/sensitive-protection/removal-cases'
      fullPath: '/sensitive-protection/removal-cases'
      preLoaderRoute: typeof AppSensitiveProtectionRemovalCasesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensitive-protection/emergency': {
      id: '/_app/sensitive-protection/emergency'
      path: '/sensitive-protection/emergency'
      fullPath: '/sensitive-protection/emergency'
      preLoaderRoute: typeof AppSensitiveProtectionEmergencyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports/$reportId': {
      id: '/_app/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof AppReportsReportIdRouteImport
      parentRoute: typeof AppReportsRoute
    }
    '/_app/protection/sources': {
      id: '/_app/protection/sources'
      path: '/protection/sources'
      fullPath: '/protection/sources'
      preLoaderRoute: typeof AppProtectionSourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/waitlist': {
      id: '/_app/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AppAdminWaitlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/sensitive-protection': {
      id: '/_app/admin/sensitive-protection'
      path: '/admin/sensitive-protection'
      fullPath: '/admin/sensitive-protection'
      preLoaderRoute: typeof AppAdminSensitiveProtectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/removal-routes': {
      id: '/_app/admin/removal-routes'
      path: '/admin/removal-routes'
      fullPath: '/admin/removal-routes'
      preLoaderRoute: typeof AppAdminRemovalRoutesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/provider-activation': {
      id: '/_app/admin/provider-activation'
      path: '/admin/provider-activation'
      fullPath: '/admin/provider-activation'
      preLoaderRoute: typeof AppAdminProviderActivationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/onboarding-reviews': {
      id: '/_app/admin/onboarding-reviews'
      path: '/admin/onboarding-reviews'
      fullPath: '/admin/onboarding-reviews'
      preLoaderRoute: typeof AppAdminOnboardingReviewsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/multimedia-health': {
      id: '/_app/admin/multimedia-health'
      path: '/admin/multimedia-health'
      fullPath: '/admin/multimedia-health'
      preLoaderRoute: typeof AppAdminMultimediaHealthRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/invites': {
      id: '/_app/admin/invites'
      path: '/admin/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AppAdminInvitesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/identity-review': {
      id: '/_app/admin/identity-review'
      path: '/admin/identity-review'
      fullPath: '/admin/identity-review'
      preLoaderRoute: typeof AppAdminIdentityReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/diagnostics': {
      id: '/_app/admin/diagnostics'
      path: '/admin/diagnostics'
      fullPath: '/admin/diagnostics'
      preLoaderRoute: typeof AppAdminDiagnosticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin/approved-sources-review': {
      id: '/_app/admin/approved-sources-review'
      path: '/admin/approved-sources-review'
      fullPath: '/admin/approved-sources-review'
      preLoaderRoute: typeof AppAdminApprovedSourcesReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sensitive-protection/results/': {
      id: '/_app/sensitive-protection/results/'
      path: '/sensitive-protection/results'
      fullPath: '/sensitive-protection/results/'
      preLoaderRoute: typeof AppSensitiveProtectionResultsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hooks/scan-orchestrator': {
      id: '/api/public/hooks/scan-orchestrator'
      path: '/api/public/hooks/scan-orchestrator'
      fullPath: '/api/public/hooks/scan-orchestrator'
      preLoaderRoute: typeof ApiPublicHooksScanOrchestratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/resend-webhook': {
      id: '/api/public/hooks/resend-webhook'
      path: '/api/public/hooks/resend-webhook'
      fullPath: '/api/public/hooks/resend-webhook'
      preLoaderRoute: typeof ApiPublicHooksResendWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/release-protection-monitor': {
      id: '/api/public/hooks/release-protection-monitor'
      path: '/api/public/hooks/release-protection-monitor'
      fullPath: '/api/public/hooks/release-protection-monitor'
      preLoaderRoute: typeof ApiPublicHooksReleaseProtectionMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/protection-scheduler-token': {
      id: '/api/public/hooks/protection-scheduler-token'
      path: '/api/public/hooks/protection-scheduler-token'
      fullPath: '/api/public/hooks/protection-scheduler-token'
      preLoaderRoute: typeof ApiPublicHooksProtectionSchedulerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/protection-autopilot': {
      id: '/api/public/hooks/protection-autopilot'
      path: '/api/public/hooks/protection-autopilot'
      fullPath: '/api/public/hooks/protection-autopilot'
      preLoaderRoute: typeof ApiPublicHooksProtectionAutopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/protection-activation-repair': {
      id: '/api/public/hooks/protection-activation-repair'
      path: '/api/public/hooks/protection-activation-repair'
      fullPath: '/api/public/hooks/protection-activation-repair'
      preLoaderRoute: typeof ApiPublicHooksProtectionActivationRepairRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/postmark-webhook': {
      id: '/api/public/hooks/postmark-webhook'
      path: '/api/public/hooks/postmark-webhook'
      fullPath: '/api/public/hooks/postmark-webhook'
      preLoaderRoute: typeof ApiPublicHooksPostmarkWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/enforcement-worker': {
      id: '/api/public/hooks/enforcement-worker'
      path: '/api/public/hooks/enforcement-worker'
      fullPath: '/api/public/hooks/enforcement-worker'
      preLoaderRoute: typeof ApiPublicHooksEnforcementWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/distribution-monitor': {
      id: '/api/public/hooks/distribution-monitor'
      path: '/api/public/hooks/distribution-monitor'
      fullPath: '/api/public/hooks/distribution-monitor'
      preLoaderRoute: typeof ApiPublicHooksDistributionMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deepfake-scan-execute': {
      id: '/api/public/hooks/deepfake-scan-execute'
      path: '/api/public/hooks/deepfake-scan-execute'
      fullPath: '/api/public/hooks/deepfake-scan-execute'
      preLoaderRoute: typeof ApiPublicHooksDeepfakeScanExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deepfake-manual-evidence-execute': {
      id: '/api/public/hooks/deepfake-manual-evidence-execute'
      path: '/api/public/hooks/deepfake-manual-evidence-execute'
      fullPath: '/api/public/hooks/deepfake-manual-evidence-execute'
      preLoaderRoute: typeof ApiPublicHooksDeepfakeManualEvidenceExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/deepfake-google-images-worker': {
      id: '/api/public/hooks/deepfake-google-images-worker'
      path: '/api/public/hooks/deepfake-google-images-worker'
      fullPath: '/api/public/hooks/deepfake-google-images-worker'
      preLoaderRoute: typeof ApiPublicHooksDeepfakeGoogleImagesWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/copyright-scan-execute': {
      id: '/api/public/hooks/copyright-scan-execute'
      path: '/api/public/hooks/copyright-scan-execute'
      fullPath: '/api/public/hooks/copyright-scan-execute'
      preLoaderRoute: typeof ApiPublicHooksCopyrightScanExecuteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/channel-watch-poll': {
      id: '/api/public/hooks/channel-watch-poll'
      path: '/api/public/hooks/channel-watch-poll'
      fullPath: '/api/public/hooks/channel-watch-poll'
      preLoaderRoute: typeof ApiPublicHooksChannelWatchPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-status': {
      id: '/api/public/hooks/automation-status'
      path: '/api/public/hooks/automation-status'
      fullPath: '/api/public/hooks/automation-status'
      preLoaderRoute: typeof ApiPublicHooksAutomationStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/automation-fetch': {
      id: '/api/public/hooks/automation-fetch'
      path: '/api/public/hooks/automation-fetch'
      fullPath: '/api/public/hooks/automation-fetch'
      preLoaderRoute: typeof ApiPublicHooksAutomationFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/approved-sources-poll': {
      id: '/api/public/hooks/approved-sources-poll'
      path: '/api/public/hooks/approved-sources-poll'
      fullPath: '/api/public/hooks/approved-sources-poll'
      preLoaderRoute: typeof ApiPublicHooksApprovedSourcesPollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/agent-assessments': {
      id: '/api/public/hooks/agent-assessments'
      path: '/api/public/hooks/agent-assessments'
      fullPath: '/api/public/hooks/agent-assessments'
      preLoaderRoute: typeof ApiPublicHooksAgentAssessmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sensitive-protection/results/$id': {
      id: '/_app/sensitive-protection/results/$id'
      path: '/sensitive-protection/results/$id'
      fullPath: '/sensitive-protection/results/$id'
      preLoaderRoute: typeof AppSensitiveProtectionResultsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppReportsRouteChildren {
  AppReportsReportIdRoute: typeof AppReportsReportIdRoute
}

const AppReportsRouteChildren: AppReportsRouteChildren = {
  AppReportsReportIdRoute: AppReportsReportIdRoute,
}

const AppReportsRouteWithChildren = AppReportsRoute._addFileChildren(
  AppReportsRouteChildren,
)

interface AppRouteChildren {
  AppAssetsRoute: typeof AppAssetsRoute
  AppCampaignsRoute: typeof AppCampaignsRoute
  AppCasesRoute: typeof AppCasesRoute
  AppChannelWatchRoute: typeof AppChannelWatchRoute
  AppCopyrightIntelRoute: typeof AppCopyrightIntelRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDeepfakeIntelRoute: typeof AppDeepfakeIntelRoute
  AppEnforcementRoute: typeof AppEnforcementRoute
  AppEvidenceVaultRoute: typeof AppEvidenceVaultRoute
  AppFaceProtectionRoute: typeof AppFaceProtectionRoute
  AppFaceReferencesRoute: typeof AppFaceReferencesRoute
  AppIntelligenceRoute: typeof AppIntelligenceRoute
  AppNarrativeIntelligenceRoute: typeof AppNarrativeIntelligenceRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppRemovalsRoute: typeof AppRemovalsRoute
  AppReportsRoute: typeof AppReportsRouteWithChildren
  AppScanRoute: typeof AppScanRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppThreatMonitoringRoute: typeof AppThreatMonitoringRoute
  AppThreatRadarRoute: typeof AppThreatRadarRoute
  AppYoutubeRemovalRoute: typeof AppYoutubeRemovalRoute
  AppAdminApprovedSourcesReviewRoute: typeof AppAdminApprovedSourcesReviewRoute
  AppAdminDiagnosticsRoute: typeof AppAdminDiagnosticsRoute
  AppAdminIdentityReviewRoute: typeof AppAdminIdentityReviewRoute
  AppAdminInvitesRoute: typeof AppAdminInvitesRoute
  AppAdminMultimediaHealthRoute: typeof AppAdminMultimediaHealthRoute
  AppAdminOnboardingReviewsRoute: typeof AppAdminOnboardingReviewsRoute
  AppAdminProviderActivationRoute: typeof AppAdminProviderActivationRoute
  AppAdminRemovalRoutesRoute: typeof AppAdminRemovalRoutesRoute
  AppAdminSensitiveProtectionRoute: typeof AppAdminSensitiveProtectionRoute
  AppAdminWaitlistRoute: typeof AppAdminWaitlistRoute
  AppProtectionSourcesRoute: typeof AppProtectionSourcesRoute
  AppSensitiveProtectionEmergencyRoute: typeof AppSensitiveProtectionEmergencyRoute
  AppSensitiveProtectionRemovalCasesRoute: typeof AppSensitiveProtectionRemovalCasesRoute
  AppSensitiveProtectionIndexRoute: typeof AppSensitiveProtectionIndexRoute
  AppSensitiveProtectionResultsIdRoute: typeof AppSensitiveProtectionResultsIdRoute
  AppSensitiveProtectionResultsIndexRoute: typeof AppSensitiveProtectionResultsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAssetsRoute: AppAssetsRoute,
  AppCampaignsRoute: AppCampaignsRoute,
  AppCasesRoute: AppCasesRoute,
  AppChannelWatchRoute: AppChannelWatchRoute,
  AppCopyrightIntelRoute: AppCopyrightIntelRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDeepfakeIntelRoute: AppDeepfakeIntelRoute,
  AppEnforcementRoute: AppEnforcementRoute,
  AppEvidenceVaultRoute: AppEvidenceVaultRoute,
  AppFaceProtectionRoute: AppFaceProtectionRoute,
  AppFaceReferencesRoute: AppFaceReferencesRoute,
  AppIntelligenceRoute: AppIntelligenceRoute,
  AppNarrativeIntelligenceRoute: AppNarrativeIntelligenceRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppRemovalsRoute: AppRemovalsRoute,
  AppReportsRoute: AppReportsRouteWithChildren,
  AppScanRoute: AppScanRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppThreatMonitoringRoute: AppThreatMonitoringRoute,
  AppThreatRadarRoute: AppThreatRadarRoute,
  AppYoutubeRemovalRoute: AppYoutubeRemovalRoute,
  AppAdminApprovedSourcesReviewRoute: AppAdminApprovedSourcesReviewRoute,
  AppAdminDiagnosticsRoute: AppAdminDiagnosticsRoute,
  AppAdminIdentityReviewRoute: AppAdminIdentityReviewRoute,
  AppAdminInvitesRoute: AppAdminInvitesRoute,
  AppAdminMultimediaHealthRoute: AppAdminMultimediaHealthRoute,
  AppAdminOnboardingReviewsRoute: AppAdminOnboardingReviewsRoute,
  AppAdminProviderActivationRoute: AppAdminProviderActivationRoute,
  AppAdminRemovalRoutesRoute: AppAdminRemovalRoutesRoute,
  AppAdminSensitiveProtectionRoute: AppAdminSensitiveProtectionRoute,
  AppAdminWaitlistRoute: AppAdminWaitlistRoute,
  AppProtectionSourcesRoute: AppProtectionSourcesRoute,
  AppSensitiveProtectionEmergencyRoute: AppSensitiveProtectionEmergencyRoute,
  AppSensitiveProtectionRemovalCasesRoute:
    AppSensitiveProtectionRemovalCasesRoute,
  AppSensitiveProtectionIndexRoute: AppSensitiveProtectionIndexRoute,
  AppSensitiveProtectionResultsIdRoute: AppSensitiveProtectionResultsIdRoute,
  AppSensitiveProtectionResultsIndexRoute:
    AppSensitiveProtectionResultsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PartnerPartnerRouteChildren {
  PartnerPartnerClientsRoute: typeof PartnerPartnerClientsRoute
  PartnerPartnerCommissionsRoute: typeof PartnerPartnerCommissionsRoute
  PartnerPartnerMarketingRoute: typeof PartnerPartnerMarketingRoute
  PartnerPartnerPaymentsRoute: typeof PartnerPartnerPaymentsRoute
  PartnerPartnerProposalsRoute: typeof PartnerPartnerProposalsRoute
  PartnerPartnerIndexRoute: typeof PartnerPartnerIndexRoute
}

const PartnerPartnerRouteChildren: PartnerPartnerRouteChildren = {
  PartnerPartnerClientsRoute: PartnerPartnerClientsRoute,
  PartnerPartnerCommissionsRoute: PartnerPartnerCommissionsRoute,
  PartnerPartnerMarketingRoute: PartnerPartnerMarketingRoute,
  PartnerPartnerPaymentsRoute: PartnerPartnerPaymentsRoute,
  PartnerPartnerProposalsRoute: PartnerPartnerProposalsRoute,
  PartnerPartnerIndexRoute: PartnerPartnerIndexRoute,
}

const PartnerPartnerRouteWithChildren = PartnerPartnerRoute._addFileChildren(
  PartnerPartnerRouteChildren,
)

interface PartnerRouteChildren {
  PartnerPartnerRoute: typeof PartnerPartnerRouteWithChildren
}

const PartnerRouteChildren: PartnerRouteChildren = {
  PartnerPartnerRoute: PartnerPartnerRouteWithChildren,
}

const PartnerRouteWithChildren =
  PartnerRoute._addFileChildren(PartnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  PartnerRoute: PartnerRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AgentRoute: AgentRoute,
  AgentAdminRoute: AgentAdminRoute,
  AgentAssessmentRoute: AgentAssessmentRoute,
  AuthRoute: AuthRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  IdentityResponseObservatoryRoute: IdentityResponseObservatoryRoute,
  MethodologyRoute: MethodologyRoute,
  NewsroomRoute: NewsroomRoute,
  OnboardingRoute: OnboardingRoute,
  PartnerApplyRoute: PartnerApplyRoute,
  PartnerStatusRoute: PartnerStatusRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  TermsRoute: TermsRoute,
  WaitinglistRoute: WaitinglistRoute,
  ApiScanRoute: ApiScanRoute,
  FaceHandoffTokenRoute: FaceHandoffTokenRoute,
  NewsroomDeepfakeVerificationGuideRoute:
    NewsroomDeepfakeVerificationGuideRoute,
  NewsroomExecutiveFirstHourPlaybookRoute:
    NewsroomExecutiveFirstHourPlaybookRoute,
  NewsroomImpersonationResponseGuideRoute:
    NewsroomImpersonationResponseGuideRoute,
  VerifySlugRoute: VerifySlugRoute,
  ApiMediaPreviewRoute: ApiMediaPreviewRoute,
  ApiPublicImageProxyRoute: ApiPublicImageProxyRoute,
  ApiPublicOnboardingCompletionBackfillRoute:
    ApiPublicOnboardingCompletionBackfillRoute,
  ApiPublicVeriffWebhookRoute: ApiPublicVeriffWebhookRoute,
  ApiPublicHooksAgentAssessmentsRoute: ApiPublicHooksAgentAssessmentsRoute,
  ApiPublicHooksApprovedSourcesPollRoute:
    ApiPublicHooksApprovedSourcesPollRoute,
  ApiPublicHooksAutomationFetchRoute: ApiPublicHooksAutomationFetchRoute,
  ApiPublicHooksAutomationStatusRoute: ApiPublicHooksAutomationStatusRoute,
  ApiPublicHooksChannelWatchPollRoute: ApiPublicHooksChannelWatchPollRoute,
  ApiPublicHooksCopyrightScanExecuteRoute:
    ApiPublicHooksCopyrightScanExecuteRoute,
  ApiPublicHooksDeepfakeGoogleImagesWorkerRoute:
    ApiPublicHooksDeepfakeGoogleImagesWorkerRoute,
  ApiPublicHooksDeepfakeManualEvidenceExecuteRoute:
    ApiPublicHooksDeepfakeManualEvidenceExecuteRoute,
  ApiPublicHooksDeepfakeScanExecuteRoute:
    ApiPublicHooksDeepfakeScanExecuteRoute,
  ApiPublicHooksDistributionMonitorRoute:
    ApiPublicHooksDistributionMonitorRoute,
  ApiPublicHooksEnforcementWorkerRoute: ApiPublicHooksEnforcementWorkerRoute,
  ApiPublicHooksPostmarkWebhookRoute: ApiPublicHooksPostmarkWebhookRoute,
  ApiPublicHooksProtectionActivationRepairRoute:
    ApiPublicHooksProtectionActivationRepairRoute,
  ApiPublicHooksProtectionAutopilotRoute:
    ApiPublicHooksProtectionAutopilotRoute,
  ApiPublicHooksProtectionSchedulerTokenRoute:
    ApiPublicHooksProtectionSchedulerTokenRoute,
  ApiPublicHooksReleaseProtectionMonitorRoute:
    ApiPublicHooksReleaseProtectionMonitorRoute,
  ApiPublicHooksResendWebhookRoute: ApiPublicHooksResendWebhookRoute,
  ApiPublicHooksScanOrchestratorRoute: ApiPublicHooksScanOrchestratorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

